// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_rules.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const listAlertIncidentsForProject = `-- name: ListAlertIncidentsForProject :many
SELECT id, project_id, rule_id, metric_name, comparison, threshold, severity,
       fired_at, resolved_at
FROM alert_incidents
WHERE project_id = $1
ORDER BY fired_at DESC, id DESC
`

func (q *Queries) ListAlertIncidentsForProject(ctx context.Context, projectID string) ([]AlertIncident, error) {
	rows, err := q.db.QueryContext(ctx, listAlertIncidentsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertIncident
	for rows.Next() {
		var i AlertIncident
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RuleID,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.Severity,
			&i.FiredAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertIncidentsForUser = `-- name: ListAlertIncidentsForUser :many
SELECT ai.id, ai.project_id, p.name AS project_name, ai.rule_id,
       ai.metric_name, ai.comparison, ai.threshold, ai.severity,
       ai.fired_at, ai.resolved_at
FROM alert_incidents ai
JOIN projects p ON p.id = ai.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE om.user_id = $1
  AND p.deleted_at IS NULL
ORDER BY ai.fired_at DESC, ai.id DESC
`

type ListAlertIncidentsForUserRow struct {
	ID          int64        `json:"id"`
	ProjectID   string       `json:"project_id"`
	ProjectName string       `json:"project_name"`
	RuleID      string       `json:"rule_id"`
	MetricName  string       `json:"metric_name"`
	Comparison  string       `json:"comparison"`
	Threshold   float64      `json:"threshold"`
	Severity    string       `json:"severity"`
	FiredAt     time.Time    `json:"fired_at"`
	ResolvedAt  sql.NullTime `json:"resolved_at"`
}

func (q *Queries) ListAlertIncidentsForUser(ctx context.Context, userID string) ([]ListAlertIncidentsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertIncidentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertIncidentsForUserRow
	for rows.Next() {
		var i ListAlertIncidentsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.RuleID,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.Severity,
			&i.FiredAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesForEvaluation = `-- name: ListAlertRulesForEvaluation :many
SELECT ar.id, ar.project_id, ar.cluster_id, ar.metric_name, ar.comparison,
       ar.threshold, ar.duration_before_firing_seconds, ar.current_state,
       ar.last_transition_at, ar.severity
FROM alert_rules ar
JOIN projects p ON p.id = ar.project_id
LEFT JOIN clusters c ON c.id = ar.cluster_id
WHERE p.deleted_at IS NULL
  AND (ar.cluster_id IS NULL OR c.deleted_at IS NULL)
ORDER BY ar.project_id, ar.id
`

func (q *Queries) ListAlertRulesForEvaluation(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRulesForEvaluation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClusterID,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationBeforeFiringSeconds,
			&i.CurrentState,
			&i.LastTransitionAt,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesForProject = `-- name: ListAlertRulesForProject :many
SELECT ar.id, ar.project_id, ar.cluster_id, ar.metric_name, ar.comparison,
       ar.threshold, ar.duration_before_firing_seconds, ar.current_state,
       ar.last_transition_at, ar.severity
FROM alert_rules ar
JOIN projects p ON p.id = ar.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
LEFT JOIN clusters c ON c.id = ar.cluster_id
WHERE ar.project_id = $1
  AND om.user_id = $2
  AND p.deleted_at IS NULL
  AND (ar.cluster_id IS NULL OR c.deleted_at IS NULL)
ORDER BY ar.id
`

type ListAlertRulesForProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListAlertRulesForProject(ctx context.Context, arg ListAlertRulesForProjectParams) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRulesForProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClusterID,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationBeforeFiringSeconds,
			&i.CurrentState,
			&i.LastTransitionAt,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRuleState = `-- name: UpdateAlertRuleState :one
WITH updated_rule AS (
    UPDATE alert_rules ar
    SET current_state = $1::text,
        last_transition_at = CASE
            WHEN ar.current_state <> $1::text THEN $2::timestamptz
            ELSE ar.last_transition_at
        END
    WHERE ar.id = $3
    RETURNING ar.id, ar.project_id, ar.cluster_id, ar.metric_name, ar.comparison, ar.threshold,
              ar.duration_before_firing_seconds, ar.current_state, ar.last_transition_at,
              ar.severity
), opened_incident AS (
    INSERT INTO alert_incidents (
        project_id, rule_id, metric_name, comparison, threshold, severity, fired_at
    )
    SELECT project_id, id, metric_name, comparison, threshold, severity,
           $2::timestamptz
    FROM updated_rule
    WHERE current_state = 'firing'
    ON CONFLICT (rule_id) WHERE resolved_at IS NULL DO NOTHING
), resolved_incident AS (
    UPDATE alert_incidents
    SET resolved_at = $2::timestamptz
    WHERE rule_id = $3
      AND resolved_at IS NULL
      AND $1::text = 'ok'
)
SELECT id, project_id, cluster_id, metric_name, comparison, threshold,
       duration_before_firing_seconds, current_state, last_transition_at,
       severity
FROM updated_rule
`

type UpdateAlertRuleStateParams struct {
	CurrentState   string    `json:"current_state"`
	TransitionedAt time.Time `json:"transitioned_at"`
	RuleID         string    `json:"rule_id"`
}

type UpdateAlertRuleStateRow struct {
	ID                          string         `json:"id"`
	ProjectID                   string         `json:"project_id"`
	ClusterID                   sql.NullString `json:"cluster_id"`
	MetricName                  string         `json:"metric_name"`
	Comparison                  string         `json:"comparison"`
	Threshold                   float64        `json:"threshold"`
	DurationBeforeFiringSeconds int64          `json:"duration_before_firing_seconds"`
	CurrentState                string         `json:"current_state"`
	LastTransitionAt            time.Time      `json:"last_transition_at"`
	Severity                    string         `json:"severity"`
}

func (q *Queries) UpdateAlertRuleState(ctx context.Context, arg UpdateAlertRuleStateParams) (UpdateAlertRuleStateRow, error) {
	row := q.db.QueryRowContext(ctx, updateAlertRuleState, arg.CurrentState, arg.TransitionedAt, arg.RuleID)
	var i UpdateAlertRuleStateRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClusterID,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationBeforeFiringSeconds,
		&i.CurrentState,
		&i.LastTransitionAt,
		&i.Severity,
	)
	return i, err
}
