// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_rules.sql

package sqlcdb

import (
	"context"
	"time"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (
    id, project_id, cluster_id, metric_name, comparison, threshold,
    duration_before_firing_seconds
)
SELECT $1::text, p.id, c.id, $2::text,
       $3::text, $4::double precision,
       $5::bigint
FROM projects p
LEFT JOIN clusters c
    ON c.id = NULLIF($6::text, '')
    AND c.project_id = p.id
    AND c.deleted_at IS NULL
WHERE p.id = $7
  AND p.user_id = $8
  AND p.deleted_at IS NULL
  AND ($6::text = '' OR c.id IS NOT NULL)
RETURNING id, project_id, cluster_id, metric_name, comparison, threshold,
          duration_before_firing_seconds, current_state, last_transition_at
`

type CreateAlertRuleParams struct {
	RuleID                      string  `json:"rule_id"`
	MetricName                  string  `json:"metric_name"`
	Comparison                  string  `json:"comparison"`
	Threshold                   float64 `json:"threshold"`
	DurationBeforeFiringSeconds int64   `json:"duration_before_firing_seconds"`
	ClusterID                   string  `json:"cluster_id"`
	ProjectID                   string  `json:"project_id"`
	UserID                      string  `json:"user_id"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, createAlertRule,
		arg.RuleID,
		arg.MetricName,
		arg.Comparison,
		arg.Threshold,
		arg.DurationBeforeFiringSeconds,
		arg.ClusterID,
		arg.ProjectID,
		arg.UserID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClusterID,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationBeforeFiringSeconds,
		&i.CurrentState,
		&i.LastTransitionAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :execrows
DELETE FROM alert_rules ar
USING projects p
WHERE ar.id = $1
  AND ar.project_id = p.id
  AND p.user_id = $2
  AND p.deleted_at IS NULL
`

type DeleteAlertRuleParams struct {
	RuleID string `json:"rule_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlertRule, arg.RuleID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAlertRulesForEvaluation = `-- name: ListAlertRulesForEvaluation :many
SELECT ar.id, ar.project_id, ar.cluster_id, ar.metric_name, ar.comparison,
       ar.threshold, ar.duration_before_firing_seconds, ar.current_state,
       ar.last_transition_at
FROM alert_rules ar
JOIN projects p ON p.id = ar.project_id
LEFT JOIN clusters c ON c.id = ar.cluster_id
WHERE p.deleted_at IS NULL
  AND (ar.cluster_id IS NULL OR c.deleted_at IS NULL)
ORDER BY ar.project_id, ar.id
`

func (q *Queries) ListAlertRulesForEvaluation(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRulesForEvaluation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClusterID,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationBeforeFiringSeconds,
			&i.CurrentState,
			&i.LastTransitionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesForProject = `-- name: ListAlertRulesForProject :many
SELECT ar.id, ar.project_id, ar.cluster_id, ar.metric_name, ar.comparison,
       ar.threshold, ar.duration_before_firing_seconds, ar.current_state,
       ar.last_transition_at
FROM alert_rules ar
JOIN projects p ON p.id = ar.project_id
LEFT JOIN clusters c ON c.id = ar.cluster_id
WHERE ar.project_id = $1
  AND p.user_id = $2
  AND p.deleted_at IS NULL
  AND (ar.cluster_id IS NULL OR c.deleted_at IS NULL)
ORDER BY ar.id
`

type ListAlertRulesForProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListAlertRulesForProject(ctx context.Context, arg ListAlertRulesForProjectParams) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRulesForProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClusterID,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationBeforeFiringSeconds,
			&i.CurrentState,
			&i.LastTransitionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRuleState = `-- name: UpdateAlertRuleState :one
UPDATE alert_rules
SET current_state = $1::text,
    last_transition_at = CASE
        WHEN current_state <> $1::text THEN $2::timestamptz
        ELSE last_transition_at
    END
WHERE id = $3
RETURNING id, project_id, cluster_id, metric_name, comparison, threshold,
          duration_before_firing_seconds, current_state, last_transition_at
`

type UpdateAlertRuleStateParams struct {
	CurrentState   string    `json:"current_state"`
	TransitionedAt time.Time `json:"transitioned_at"`
	RuleID         string    `json:"rule_id"`
}

func (q *Queries) UpdateAlertRuleState(ctx context.Context, arg UpdateAlertRuleStateParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, updateAlertRuleState, arg.CurrentState, arg.TransitionedAt, arg.RuleID)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClusterID,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationBeforeFiringSeconds,
		&i.CurrentState,
		&i.LastTransitionAt,
	)
	return i, err
}
