// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clusters.sql

package sqlcdb

import (
	"context"
	"encoding/json"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    id, project_id, host_id, name, postgres_version, parameters,
    replica_count, pgbouncer_enabled
)
SELECT $1::text, p.id, h.id, $2::text,
       $3::text, $4::jsonb,
       $5::integer, $6::boolean
FROM projects p
JOIN hosts h ON h.id = $7 AND h.user_id = $8
WHERE p.id = $9 AND p.user_id = $8 AND p.deleted_at IS NULL
RETURNING id, project_id, host_id, name, postgres_version, parameters,
          replica_count, pgbouncer_enabled, created_at, updated_at, deleted_at
`

type CreateClusterParams struct {
	ClusterID        string          `json:"cluster_id"`
	Name             string          `json:"name"`
	PostgresVersion  string          `json:"postgres_version"`
	Parameters       json.RawMessage `json:"parameters"`
	ReplicaCount     int32           `json:"replica_count"`
	PgbouncerEnabled bool            `json:"pgbouncer_enabled"`
	HostID           string          `json:"host_id"`
	UserID           string          `json:"user_id"`
	ProjectID        string          `json:"project_id"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster,
		arg.ClusterID,
		arg.Name,
		arg.PostgresVersion,
		arg.Parameters,
		arg.ReplicaCount,
		arg.PgbouncerEnabled,
		arg.HostID,
		arg.UserID,
		arg.ProjectID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCluster = `-- name: GetCluster :one
SELECT c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
       c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at
FROM clusters c
JOIN projects p ON p.id = c.project_id
WHERE c.id = $1 AND p.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetClusterParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetCluster(ctx context.Context, arg GetClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, getCluster, arg.ID, arg.UserID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveClustersForProject = `-- name: ListActiveClustersForProject :many
SELECT c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
       c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at
FROM clusters c
JOIN projects p ON p.id = c.project_id
WHERE c.project_id = $1 AND p.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY c.id
`

type ListActiveClustersForProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListActiveClustersForProject(ctx context.Context, arg ListActiveClustersForProjectParams) ([]Cluster, error) {
	rows, err := q.db.QueryContext(ctx, listActiveClustersForProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.Name,
			&i.PostgresVersion,
			&i.Parameters,
			&i.ReplicaCount,
			&i.PgbouncerEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusters = `-- name: ListClusters :many
SELECT c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
       c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at
FROM clusters c
JOIN projects p ON p.id = c.project_id
WHERE c.project_id = $1 AND p.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY c.created_at, c.id
`

type ListClustersParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListClusters(ctx context.Context, arg ListClustersParams) ([]Cluster, error) {
	rows, err := q.db.QueryContext(ctx, listClusters, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.Name,
			&i.PostgresVersion,
			&i.Parameters,
			&i.ReplicaCount,
			&i.PgbouncerEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCluster = `-- name: SoftDeleteCluster :one
UPDATE clusters c
SET deleted_at = NOW(), updated_at = NOW()
FROM projects p
WHERE c.id = $1 AND c.project_id = p.id AND p.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id
`

type SoftDeleteClusterParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type SoftDeleteClusterRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	HostID    string `json:"host_id"`
}

func (q *Queries) SoftDeleteCluster(ctx context.Context, arg SoftDeleteClusterParams) (SoftDeleteClusterRow, error) {
	row := q.db.QueryRowContext(ctx, softDeleteCluster, arg.ID, arg.UserID)
	var i SoftDeleteClusterRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.HostID)
	return i, err
}

const softDeleteClustersForProject = `-- name: SoftDeleteClustersForProject :exec
UPDATE clusters c
SET deleted_at = NOW(), updated_at = NOW()
FROM projects p
WHERE c.project_id = $1 AND c.project_id = p.id AND p.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
`

type SoftDeleteClustersForProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SoftDeleteClustersForProject(ctx context.Context, arg SoftDeleteClustersForProjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteClustersForProject, arg.ProjectID, arg.UserID)
	return err
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE clusters c
SET name = $3,
    postgres_version = $4,
    parameters = $5,
    replica_count = $6,
    pgbouncer_enabled = $7,
    updated_at = NOW()
FROM projects p
WHERE c.id = $1 AND c.project_id = p.id AND p.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
          c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at
`

type UpdateClusterParams struct {
	ID               string          `json:"id"`
	UserID           string          `json:"user_id"`
	Name             string          `json:"name"`
	PostgresVersion  string          `json:"postgres_version"`
	Parameters       json.RawMessage `json:"parameters"`
	ReplicaCount     int32           `json:"replica_count"`
	PgbouncerEnabled bool            `json:"pgbouncer_enabled"`
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, updateCluster,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.PostgresVersion,
		arg.Parameters,
		arg.ReplicaCount,
		arg.PgbouncerEnabled,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
