// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clusters.sql

package sqlcdb

import (
	"context"
	"encoding/json"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    id, project_id, host_id, name, postgres_version, parameters,
    replica_count, replica_ids, enabled_extensions, pgbouncer_enabled, pgbouncer_pool_mode,
    pgbouncer_max_connections, pgbouncer_publish_address, pgbouncer_publish_port,
    pgbackrest_enabled, pgbackrest_repo_path,
    pgbackrest_retention_full, pgbackrest_retention_diff,
    pgbackrest_full_interval_seconds, pgbackrest_diff_interval_seconds,
    pgbackrest_incr_interval_seconds, pg_hba_rules
)
SELECT $1::text, p.id, h.id, $2::text,
       $3::text, $4::jsonb,
       $5::integer, $6::jsonb, $7::jsonb,
       $8::boolean, $9::text,
       $10::integer, $11::text,
       $12::integer,
       $13::boolean, $14::text,
       $15::bigint, $16::bigint,
       $17::bigint, $18::bigint,
       $19::bigint, $20::jsonb
FROM projects p
JOIN hosts h ON h.id = $21 AND h.user_id = $22
JOIN organization_memberships om
  ON om.organization_id = p.organization_id AND om.user_id = $22
WHERE p.id = $23 AND p.deleted_at IS NULL
RETURNING id, project_id, host_id, name, postgres_version, parameters,
           replica_count, pgbouncer_enabled, created_at, updated_at, deleted_at,
          pgbackrest_enabled, pgbackrest_repo_path,
          pgbackrest_retention_full, pgbackrest_retention_diff,
          pgbackrest_full_interval_seconds, pgbackrest_diff_interval_seconds,
           pgbackrest_incr_interval_seconds, replica_ids, enabled_extensions,
             pgbouncer_pool_mode, pgbouncer_max_connections, pg_hba_rules, restart_generation,
             pgbouncer_publish_address, pgbouncer_publish_port
`

type CreateClusterParams struct {
	ClusterID                     string          `json:"cluster_id"`
	Name                          string          `json:"name"`
	PostgresVersion               string          `json:"postgres_version"`
	Parameters                    json.RawMessage `json:"parameters"`
	ReplicaCount                  int32           `json:"replica_count"`
	ReplicaIds                    json.RawMessage `json:"replica_ids"`
	EnabledExtensions             json.RawMessage `json:"enabled_extensions"`
	PgbouncerEnabled              bool            `json:"pgbouncer_enabled"`
	PgbouncerPoolMode             string          `json:"pgbouncer_pool_mode"`
	PgbouncerMaxConnections       int32           `json:"pgbouncer_max_connections"`
	PgbouncerPublishAddress       string          `json:"pgbouncer_publish_address"`
	PgbouncerPublishPort          int32           `json:"pgbouncer_publish_port"`
	PgbackrestEnabled             bool            `json:"pgbackrest_enabled"`
	PgbackrestRepoPath            string          `json:"pgbackrest_repo_path"`
	PgbackrestRetentionFull       int64           `json:"pgbackrest_retention_full"`
	PgbackrestRetentionDiff       int64           `json:"pgbackrest_retention_diff"`
	PgbackrestFullIntervalSeconds int64           `json:"pgbackrest_full_interval_seconds"`
	PgbackrestDiffIntervalSeconds int64           `json:"pgbackrest_diff_interval_seconds"`
	PgbackrestIncrIntervalSeconds int64           `json:"pgbackrest_incr_interval_seconds"`
	PgHbaRules                    json.RawMessage `json:"pg_hba_rules"`
	HostID                        string          `json:"host_id"`
	UserID                        string          `json:"user_id"`
	ProjectID                     string          `json:"project_id"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster,
		arg.ClusterID,
		arg.Name,
		arg.PostgresVersion,
		arg.Parameters,
		arg.ReplicaCount,
		arg.ReplicaIds,
		arg.EnabledExtensions,
		arg.PgbouncerEnabled,
		arg.PgbouncerPoolMode,
		arg.PgbouncerMaxConnections,
		arg.PgbouncerPublishAddress,
		arg.PgbouncerPublishPort,
		arg.PgbackrestEnabled,
		arg.PgbackrestRepoPath,
		arg.PgbackrestRetentionFull,
		arg.PgbackrestRetentionDiff,
		arg.PgbackrestFullIntervalSeconds,
		arg.PgbackrestDiffIntervalSeconds,
		arg.PgbackrestIncrIntervalSeconds,
		arg.PgHbaRules,
		arg.HostID,
		arg.UserID,
		arg.ProjectID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const getCluster = `-- name: GetCluster :one
SELECT c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
       c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
       c.pgbackrest_enabled, c.pgbackrest_repo_path,
       c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
       c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
       c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
         c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
         c.pgbouncer_publish_address, c.pgbouncer_publish_port
FROM clusters c
JOIN projects p ON p.id = c.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE c.id = $1 AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetClusterParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetCluster(ctx context.Context, arg GetClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, getCluster, arg.ID, arg.UserID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const getClusterMutationResource = `-- name: GetClusterMutationResource :one
SELECT c.id, om.role
FROM clusters c
JOIN projects p ON p.id = c.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE c.id = $1 AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
FOR UPDATE OF c
`

type GetClusterMutationResourceParams struct {
	ClusterID string `json:"cluster_id"`
	UserID    string `json:"user_id"`
}

type GetClusterMutationResourceRow struct {
	ID   string           `json:"id"`
	Role OrganizationRole `json:"role"`
}

func (q *Queries) GetClusterMutationResource(ctx context.Context, arg GetClusterMutationResourceParams) (GetClusterMutationResourceRow, error) {
	row := q.db.QueryRowContext(ctx, getClusterMutationResource, arg.ClusterID, arg.UserID)
	var i GetClusterMutationResourceRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const listActiveClustersForProject = `-- name: ListActiveClustersForProject :many
SELECT c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
       c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
       c.pgbackrest_enabled, c.pgbackrest_repo_path,
       c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
       c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
       c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
         c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
         c.pgbouncer_publish_address, c.pgbouncer_publish_port
FROM clusters c
JOIN projects p ON p.id = c.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE c.project_id = $1 AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY c.id
`

type ListActiveClustersForProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListActiveClustersForProject(ctx context.Context, arg ListActiveClustersForProjectParams) ([]Cluster, error) {
	rows, err := q.db.QueryContext(ctx, listActiveClustersForProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.Name,
			&i.PostgresVersion,
			&i.Parameters,
			&i.ReplicaCount,
			&i.PgbouncerEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PgbackrestEnabled,
			&i.PgbackrestRepoPath,
			&i.PgbackrestRetentionFull,
			&i.PgbackrestRetentionDiff,
			&i.PgbackrestFullIntervalSeconds,
			&i.PgbackrestDiffIntervalSeconds,
			&i.PgbackrestIncrIntervalSeconds,
			&i.ReplicaIds,
			&i.EnabledExtensions,
			&i.PgbouncerPoolMode,
			&i.PgbouncerMaxConnections,
			&i.PgHbaRules,
			&i.RestartGeneration,
			&i.PgbouncerPublishAddress,
			&i.PgbouncerPublishPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusters = `-- name: ListClusters :many
SELECT c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
       c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
       c.pgbackrest_enabled, c.pgbackrest_repo_path,
       c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
       c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
       c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
         c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
         c.pgbouncer_publish_address, c.pgbouncer_publish_port
FROM clusters c
JOIN projects p ON p.id = c.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE c.project_id = $1 AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY c.created_at, c.id
`

type ListClustersParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListClusters(ctx context.Context, arg ListClustersParams) ([]Cluster, error) {
	rows, err := q.db.QueryContext(ctx, listClusters, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.Name,
			&i.PostgresVersion,
			&i.Parameters,
			&i.ReplicaCount,
			&i.PgbouncerEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PgbackrestEnabled,
			&i.PgbackrestRepoPath,
			&i.PgbackrestRetentionFull,
			&i.PgbackrestRetentionDiff,
			&i.PgbackrestFullIntervalSeconds,
			&i.PgbackrestDiffIntervalSeconds,
			&i.PgbackrestIncrIntervalSeconds,
			&i.ReplicaIds,
			&i.EnabledExtensions,
			&i.PgbouncerPoolMode,
			&i.PgbouncerMaxConnections,
			&i.PgHbaRules,
			&i.RestartGeneration,
			&i.PgbouncerPublishAddress,
			&i.PgbouncerPublishPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectClusterMutationResources = `-- name: ListProjectClusterMutationResources :many
SELECT c.id
FROM clusters c
JOIN projects p ON p.id = c.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE c.project_id = $1 AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY c.id
FOR UPDATE OF c
`

type ListProjectClusterMutationResourcesParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListProjectClusterMutationResources(ctx context.Context, arg ListProjectClusterMutationResourcesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectClusterMutationResources, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCluster = `-- name: SoftDeleteCluster :one
UPDATE clusters c
SET deleted_at = NOW(), updated_at = NOW()
FROM projects p, organization_memberships om
WHERE c.id = $1 AND c.project_id = p.id
  AND om.organization_id = p.organization_id AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id
`

type SoftDeleteClusterParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type SoftDeleteClusterRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	HostID    string `json:"host_id"`
}

func (q *Queries) SoftDeleteCluster(ctx context.Context, arg SoftDeleteClusterParams) (SoftDeleteClusterRow, error) {
	row := q.db.QueryRowContext(ctx, softDeleteCluster, arg.ID, arg.UserID)
	var i SoftDeleteClusterRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.HostID)
	return i, err
}

const softDeleteClustersForProject = `-- name: SoftDeleteClustersForProject :exec
UPDATE clusters c
SET deleted_at = NOW(), updated_at = NOW()
FROM projects p, organization_memberships om
WHERE c.project_id = $1 AND c.project_id = p.id
  AND om.organization_id = p.organization_id AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
`

type SoftDeleteClustersForProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SoftDeleteClustersForProject(ctx context.Context, arg SoftDeleteClustersForProjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteClustersForProject, arg.ProjectID, arg.UserID)
	return err
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE clusters c
SET name = $3,
    postgres_version = $4,
    parameters = $5,
    replica_count = $6,
    replica_ids = $7,
    enabled_extensions = $8,
    pgbouncer_enabled = $9,
    pgbouncer_pool_mode = $10,
    pgbouncer_max_connections = $11,
    pgbouncer_publish_address = $12,
    pgbouncer_publish_port = $13,
    pgbackrest_enabled = $14,
    pgbackrest_repo_path = $15,
    pgbackrest_retention_full = $16,
    pgbackrest_retention_diff = $17,
    pgbackrest_full_interval_seconds = $18,
    pgbackrest_diff_interval_seconds = $19,
    pgbackrest_incr_interval_seconds = $20,
    pg_hba_rules = $21,
    updated_at = NOW()
FROM projects p, organization_memberships om
WHERE c.id = $1 AND c.project_id = p.id
  AND om.organization_id = p.organization_id AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
           c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
          c.pgbackrest_enabled, c.pgbackrest_repo_path,
          c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
          c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
           c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
             c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
             c.pgbouncer_publish_address, c.pgbouncer_publish_port
`

type UpdateClusterParams struct {
	ID                            string          `json:"id"`
	UserID                        string          `json:"user_id"`
	Name                          string          `json:"name"`
	PostgresVersion               string          `json:"postgres_version"`
	Parameters                    json.RawMessage `json:"parameters"`
	ReplicaCount                  int32           `json:"replica_count"`
	ReplicaIds                    json.RawMessage `json:"replica_ids"`
	EnabledExtensions             json.RawMessage `json:"enabled_extensions"`
	PgbouncerEnabled              bool            `json:"pgbouncer_enabled"`
	PgbouncerPoolMode             string          `json:"pgbouncer_pool_mode"`
	PgbouncerMaxConnections       int32           `json:"pgbouncer_max_connections"`
	PgbouncerPublishAddress       string          `json:"pgbouncer_publish_address"`
	PgbouncerPublishPort          int32           `json:"pgbouncer_publish_port"`
	PgbackrestEnabled             bool            `json:"pgbackrest_enabled"`
	PgbackrestRepoPath            string          `json:"pgbackrest_repo_path"`
	PgbackrestRetentionFull       int64           `json:"pgbackrest_retention_full"`
	PgbackrestRetentionDiff       int64           `json:"pgbackrest_retention_diff"`
	PgbackrestFullIntervalSeconds int64           `json:"pgbackrest_full_interval_seconds"`
	PgbackrestDiffIntervalSeconds int64           `json:"pgbackrest_diff_interval_seconds"`
	PgbackrestIncrIntervalSeconds int64           `json:"pgbackrest_incr_interval_seconds"`
	PgHbaRules                    json.RawMessage `json:"pg_hba_rules"`
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, updateCluster,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.PostgresVersion,
		arg.Parameters,
		arg.ReplicaCount,
		arg.ReplicaIds,
		arg.EnabledExtensions,
		arg.PgbouncerEnabled,
		arg.PgbouncerPoolMode,
		arg.PgbouncerMaxConnections,
		arg.PgbouncerPublishAddress,
		arg.PgbouncerPublishPort,
		arg.PgbackrestEnabled,
		arg.PgbackrestRepoPath,
		arg.PgbackrestRetentionFull,
		arg.PgbackrestRetentionDiff,
		arg.PgbackrestFullIntervalSeconds,
		arg.PgbackrestDiffIntervalSeconds,
		arg.PgbackrestIncrIntervalSeconds,
		arg.PgHbaRules,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const updateClusterParameters = `-- name: UpdateClusterParameters :one
UPDATE clusters c
SET parameters = $1::jsonb,
    updated_at = NOW()
FROM projects p, organization_memberships om
WHERE c.id = $2 AND c.project_id = p.id
  AND om.organization_id = p.organization_id AND om.user_id = $3
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
          c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
          c.pgbackrest_enabled, c.pgbackrest_repo_path,
          c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
          c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
          c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
          c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
          c.pgbouncer_publish_address, c.pgbouncer_publish_port
`

type UpdateClusterParametersParams struct {
	Parameters json.RawMessage `json:"parameters"`
	ClusterID  string          `json:"cluster_id"`
	UserID     string          `json:"user_id"`
}

func (q *Queries) UpdateClusterParameters(ctx context.Context, arg UpdateClusterParametersParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, updateClusterParameters, arg.Parameters, arg.ClusterID, arg.UserID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const updateClusterPgBouncer = `-- name: UpdateClusterPgBouncer :one
UPDATE clusters c
SET pgbouncer_pool_mode = $1::text,
    pgbouncer_max_connections = $2::integer,
    pgbouncer_publish_address = $3::text,
    pgbouncer_publish_port = $4::integer,
    updated_at = NOW()
WHERE c.id = $5 AND c.pgbouncer_enabled AND c.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
          c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
          c.pgbackrest_enabled, c.pgbackrest_repo_path,
          c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
          c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
          c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
            c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
            c.pgbouncer_publish_address, c.pgbouncer_publish_port
`

type UpdateClusterPgBouncerParams struct {
	PgbouncerPoolMode       string `json:"pgbouncer_pool_mode"`
	PgbouncerMaxConnections int32  `json:"pgbouncer_max_connections"`
	PgbouncerPublishAddress string `json:"pgbouncer_publish_address"`
	PgbouncerPublishPort    int32  `json:"pgbouncer_publish_port"`
	ClusterID               string `json:"cluster_id"`
}

func (q *Queries) UpdateClusterPgBouncer(ctx context.Context, arg UpdateClusterPgBouncerParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, updateClusterPgBouncer,
		arg.PgbouncerPoolMode,
		arg.PgbouncerMaxConnections,
		arg.PgbouncerPublishAddress,
		arg.PgbouncerPublishPort,
		arg.ClusterID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const updateClusterPgHba = `-- name: UpdateClusterPgHba :one
UPDATE clusters c
SET pg_hba_rules = $1::jsonb,
    updated_at = NOW()
WHERE c.id = $2 AND c.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
          c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
          c.pgbackrest_enabled, c.pgbackrest_repo_path,
          c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
          c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
          c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
           c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
           c.pgbouncer_publish_address, c.pgbouncer_publish_port
`

type UpdateClusterPgHbaParams struct {
	PgHbaRules json.RawMessage `json:"pg_hba_rules"`
	ClusterID  string          `json:"cluster_id"`
}

func (q *Queries) UpdateClusterPgHba(ctx context.Context, arg UpdateClusterPgHbaParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, updateClusterPgHba, arg.PgHbaRules, arg.ClusterID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const updateClusterRestart = `-- name: UpdateClusterRestart :one
UPDATE clusters c
SET restart_generation = restart_generation + 1,
    updated_at = NOW()
FROM projects p, organization_memberships om
WHERE c.id = $1 AND c.project_id = p.id
  AND om.organization_id = p.organization_id AND om.user_id = $2
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
RETURNING c.id, c.project_id, c.host_id, c.name, c.postgres_version, c.parameters,
          c.replica_count, c.pgbouncer_enabled, c.created_at, c.updated_at, c.deleted_at,
          c.pgbackrest_enabled, c.pgbackrest_repo_path,
          c.pgbackrest_retention_full, c.pgbackrest_retention_diff,
          c.pgbackrest_full_interval_seconds, c.pgbackrest_diff_interval_seconds,
          c.pgbackrest_incr_interval_seconds, c.replica_ids, c.enabled_extensions,
          c.pgbouncer_pool_mode, c.pgbouncer_max_connections, c.pg_hba_rules, c.restart_generation,
          c.pgbouncer_publish_address, c.pgbouncer_publish_port
`

type UpdateClusterRestartParams struct {
	ClusterID string `json:"cluster_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateClusterRestart(ctx context.Context, arg UpdateClusterRestartParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, updateClusterRestart, arg.ClusterID, arg.UserID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}
