// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: desired_states.sql

package sqlcdb

import (
	"context"
	"encoding/json"
)

const createDesiredState = `-- name: CreateDesiredState :one
INSERT INTO desired_states (host_id, cluster_id, operation, state)
VALUES ($1, $2, $3, $4)
RETURNING id, host_id, cluster_id, operation, state, created_at
`

type CreateDesiredStateParams struct {
	HostID    string          `json:"host_id"`
	ClusterID string          `json:"cluster_id"`
	Operation string          `json:"operation"`
	State     json.RawMessage `json:"state"`
}

func (q *Queries) CreateDesiredState(ctx context.Context, arg CreateDesiredStateParams) (DesiredState, error) {
	row := q.db.QueryRowContext(ctx, createDesiredState,
		arg.HostID,
		arg.ClusterID,
		arg.Operation,
		arg.State,
	)
	var i DesiredState
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ClusterID,
		&i.Operation,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentDesiredStatesForHost = `-- name: ListCurrentDesiredStatesForHost :many
SELECT latest.id, latest.host_id, latest.cluster_id, latest.operation,
       latest.state, latest.created_at
FROM (
    SELECT DISTINCT ON (ds.cluster_id)
           ds.id, ds.host_id, ds.cluster_id, ds.operation, ds.state, ds.created_at
    FROM desired_states ds
    WHERE ds.host_id = $1
    ORDER BY ds.cluster_id, ds.id DESC
) latest
WHERE latest.operation = 'upsert'
ORDER BY latest.cluster_id
`

func (q *Queries) ListCurrentDesiredStatesForHost(ctx context.Context, hostID string) ([]DesiredState, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentDesiredStatesForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DesiredState
	for rows.Next() {
		var i DesiredState
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ClusterID,
			&i.Operation,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDesiredStateHistory = `-- name: ListDesiredStateHistory :many
SELECT ds.id, ds.host_id, ds.cluster_id, ds.operation, ds.state, ds.created_at
FROM desired_states ds
JOIN clusters c ON c.id = ds.cluster_id
JOIN projects p ON p.id = c.project_id
WHERE ds.cluster_id = $1 AND p.user_id = $2
ORDER BY ds.id
`

type ListDesiredStateHistoryParams struct {
	ClusterID string `json:"cluster_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListDesiredStateHistory(ctx context.Context, arg ListDesiredStateHistoryParams) ([]DesiredState, error) {
	rows, err := q.db.QueryContext(ctx, listDesiredStateHistory, arg.ClusterID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DesiredState
	for rows.Next() {
		var i DesiredState
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ClusterID,
			&i.Operation,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
