// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package sqlcdb

import (
	"context"
	"time"
)

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (id, user_id, token_hash, token_expires_at, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, token_expires_at, status, created_at, connected_at
`

type CreateHostParams struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	TokenHash      []byte    `json:"token_hash"`
	TokenExpiresAt time.Time `json:"token_expires_at"`
	Status         string    `json:"status"`
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, createHost,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.Status,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedAt,
	)
	return i, err
}

const deleteUnusedHost = `-- name: DeleteUnusedHost :execrows
WITH target_host AS (
    SELECT h.id
    FROM hosts h
    WHERE h.id = $1
      AND h.user_id = $2
      AND h.status = 'never_connected'
      AND NOT EXISTS (
          SELECT 1 FROM clusters c
          WHERE c.host_id = h.id AND c.deleted_at IS NULL
      )
), deleted_states AS (
    DELETE FROM desired_states ds
    USING clusters c, target_host h
    WHERE ds.cluster_id = c.id AND c.host_id = h.id
), deleted_clusters AS (
    DELETE FROM clusters c
    USING target_host h
    WHERE c.host_id = h.id
)
DELETE FROM hosts h
USING target_host target
WHERE h.id = target.id
`

type DeleteUnusedHostParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteUnusedHost(ctx context.Context, arg DeleteUnusedHostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedHost, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHost = `-- name: GetHost :one
SELECT id, user_id, token_hash, token_expires_at, status, created_at, connected_at
FROM hosts
WHERE id = $1
`

func (q *Queries) GetHost(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedAt,
	)
	return i, err
}

const getHostByTokenHash = `-- name: GetHostByTokenHash :one
SELECT id, user_id, token_hash, token_expires_at, status, created_at, connected_at
FROM hosts
WHERE token_hash = $1
`

func (q *Queries) GetHostByTokenHash(ctx context.Context, tokenHash []byte) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByTokenHash, tokenHash)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedAt,
	)
	return i, err
}

const revokeUnusedHostToken = `-- name: RevokeUnusedHostToken :execrows
UPDATE hosts
SET token_hash = $1,
    token_expires_at = $2
WHERE id = $3
  AND user_id = $4
  AND status = 'never_connected'
`

type RevokeUnusedHostTokenParams struct {
	TokenHash      []byte    `json:"token_hash"`
	TokenExpiresAt time.Time `json:"token_expires_at"`
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) RevokeUnusedHostToken(ctx context.Context, arg RevokeUnusedHostTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUnusedHostToken,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rotateHostToken = `-- name: RotateHostToken :one
UPDATE hosts
SET token_hash = $1,
    token_expires_at = $2
WHERE id = $3
  AND user_id = $4
RETURNING status
`

type RotateHostTokenParams struct {
	TokenHash      []byte    `json:"token_hash"`
	TokenExpiresAt time.Time `json:"token_expires_at"`
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) RotateHostToken(ctx context.Context, arg RotateHostTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, rotateHostToken,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.ID,
		arg.UserID,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateHostStatus = `-- name: UpdateHostStatus :exec
UPDATE hosts
SET status = $2,
    connected_at = CASE WHEN $2 = 'online' THEN NOW() ELSE connected_at END
WHERE id = $1
`

type UpdateHostStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHostStatus, arg.ID, arg.Status)
	return err
}
