// Code generated by sqlc. DO NOT EDIT.

package sqlcdb

import (
	"context"
	"time"
)

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (id, user_id, token_hash, token_expires_at, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, token_expires_at, status, created_at, connected_at
`

type CreateHostParams struct {
	ID             string
	UserID         string
	TokenHash      []byte
	TokenExpiresAt time.Time
	Status         string
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, createHost,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.TokenExpiresAt,
		arg.Status,
	)
	var host Host
	err := row.Scan(
		&host.ID,
		&host.UserID,
		&host.TokenHash,
		&host.TokenExpiresAt,
		&host.Status,
		&host.CreatedAt,
		&host.ConnectedAt,
	)
	return host, err
}

const getHostByTokenHash = `-- name: GetHostByTokenHash :one
SELECT id, user_id, token_hash, token_expires_at, status, created_at, connected_at
FROM hosts
WHERE token_hash = $1
`

func (q *Queries) GetHostByTokenHash(ctx context.Context, tokenHash []byte) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByTokenHash, tokenHash)
	var host Host
	err := row.Scan(
		&host.ID,
		&host.UserID,
		&host.TokenHash,
		&host.TokenExpiresAt,
		&host.Status,
		&host.CreatedAt,
		&host.ConnectedAt,
	)
	return host, err
}

const updateHostStatus = `-- name: UpdateHostStatus :exec
UPDATE hosts
SET status = $2,
    connected_at = CASE WHEN $2 = 'online' THEN NOW() ELSE connected_at END
WHERE id = $1
`

type UpdateHostStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHostStatus, arg.ID, arg.Status)
	return err
}
