// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AgentReport struct {
	HostID       string          `json:"host_id"`
	ActualState  json.RawMessage `json:"actual_state"`
	HealthReport json.RawMessage `json:"health_report"`
	ReportedAt   time.Time       `json:"reported_at"`
}

type Cluster struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	HostID           string          `json:"host_id"`
	Name             string          `json:"name"`
	PostgresVersion  string          `json:"postgres_version"`
	Parameters       json.RawMessage `json:"parameters"`
	ReplicaCount     int32           `json:"replica_count"`
	PgbouncerEnabled bool            `json:"pgbouncer_enabled"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
}

type ClusterReport struct {
	HostID       string          `json:"host_id"`
	ClusterID    string          `json:"cluster_id"`
	ActualState  json.RawMessage `json:"actual_state"`
	HealthStatus string          `json:"health_status"`
	ReportedAt   time.Time       `json:"reported_at"`
}

type DesiredState struct {
	ID        int64           `json:"id"`
	HostID    string          `json:"host_id"`
	ClusterID string          `json:"cluster_id"`
	Operation string          `json:"operation"`
	State     json.RawMessage `json:"state"`
	CreatedAt time.Time       `json:"created_at"`
}

type Host struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	TokenHash      []byte       `json:"token_hash"`
	TokenExpiresAt time.Time    `json:"token_expires_at"`
	Status         string       `json:"status"`
	CreatedAt      time.Time    `json:"created_at"`
	ConnectedAt    sql.NullTime `json:"connected_at"`
}

type Project struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
