// Code generated by sqlc. DO NOT EDIT.

package sqlcdb

import (
	"database/sql"
	"time"
)

type Host struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	TokenHash      []byte       `json:"token_hash"`
	TokenExpiresAt time.Time    `json:"token_expires_at"`
	Status         string       `json:"status"`
	CreatedAt      time.Time    `json:"created_at"`
	ConnectedAt    sql.NullTime `json:"connected_at"`
}
