// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           OrganizationRole `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRowContext(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
WITH generated AS (
    SELECT gen_random_uuid() AS id
), values_to_insert AS (
    SELECT id,
           $1::text AS name,
           COALESCE(
               NULLIF(TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER($1::text), '[^a-z0-9]+', '-', 'g')), ''),
               'workspace'
           ) || '-' || REPLACE(id::text, '-', '') AS slug
    FROM generated
)
INSERT INTO organizations (id, name, slug)
SELECT id, name, slug
FROM values_to_insert
RETURNING id, name, slug, created_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipForUserAndOrg = `-- name: GetMembershipForUserAndOrg :one
SELECT id, organization_id, user_id, role, created_at
FROM organization_memberships
WHERE organization_id = $1 AND user_id = $2
`

type GetMembershipForUserAndOrgParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetMembershipForUserAndOrg(ctx context.Context, arg GetMembershipForUserAndOrgParams) (OrganizationMembership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipForUserAndOrg, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at
FROM organizations
WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersForOrganization = `-- name: ListMembersForOrganization :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at,
       COALESCE(u.email, oi.provider_email) AS email
FROM organization_memberships om
JOIN users u ON u.id = om.user_id
LEFT JOIN LATERAL (
    SELECT provider_email
    FROM oauth_identities
    WHERE user_id = u.id AND provider_email IS NOT NULL
    ORDER BY created_at, provider, provider_user_id
    LIMIT 1
) oi ON TRUE
WHERE om.organization_id = $1
  AND u.deleted_at IS NULL
ORDER BY om.created_at, om.id
`

type ListMembersForOrganizationRow struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           OrganizationRole `json:"role"`
	CreatedAt      time.Time        `json:"created_at"`
	Email          sql.NullString   `json:"email"`
}

func (q *Queries) ListMembersForOrganization(ctx context.Context, organizationID string) ([]ListMembersForOrganizationRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersForOrganizationRow
	for rows.Next() {
		var i ListMembersForOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.created_at
FROM organizations o
JOIN organization_memberships om ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY o.created_at, o.id
`

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForOrganization = `-- name: ListProjectsForOrganization :many
SELECT id, user_id, name, created_at, updated_at, deleted_at, organization_id
FROM projects
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListProjectsForOrganization(ctx context.Context, organizationID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
