// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           OrganizationRole `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRowContext(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
WITH generated AS (
    SELECT gen_random_uuid() AS id
), values_to_insert AS (
    SELECT id,
           $1::text AS name,
           COALESCE(
               NULLIF(TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER($1::text), '[^a-z0-9]+', '-', 'g')), ''),
               'workspace'
           ) || '-' || REPLACE(id::text, '-', '') AS slug
    FROM generated
)
INSERT INTO organizations (id, name, slug)
SELECT id, name, slug
FROM values_to_insert
RETURNING id, name, slug, created_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :execrows
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrganization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMembershipForUserAndOrg = `-- name: GetMembershipForUserAndOrg :one
SELECT id, organization_id, user_id, role, created_at
FROM organization_memberships
WHERE organization_id = $1 AND user_id = $2
`

type GetMembershipForUserAndOrgParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetMembershipForUserAndOrg(ctx context.Context, arg GetMembershipForUserAndOrgParams) (OrganizationMembership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipForUserAndOrg, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT o.id, o.name, o.slug, o.created_at
FROM organizations o
JOIN organization_memberships requester
  ON requester.organization_id = o.id
 AND requester.user_id = $1
WHERE o.id = $2
`

type GetOrganizationByIDParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetOrganizationByID(ctx context.Context, arg GetOrganizationByIDParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByID, arg.UserID, arg.OrganizationID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at
FROM organizations
WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationDeletionState = `-- name: GetOrganizationDeletionState :one
SELECT om.role,
       EXISTS (SELECT 1 FROM projects p WHERE p.organization_id = o.id) AS has_projects
FROM organizations o
JOIN organization_memberships om ON om.organization_id = o.id
WHERE o.id = $1
  AND om.user_id = $2
FOR UPDATE OF o
`

type GetOrganizationDeletionStateParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

type GetOrganizationDeletionStateRow struct {
	Role        OrganizationRole `json:"role"`
	HasProjects bool             `json:"has_projects"`
}

func (q *Queries) GetOrganizationDeletionState(ctx context.Context, arg GetOrganizationDeletionStateParams) (GetOrganizationDeletionStateRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationDeletionState, arg.OrganizationID, arg.UserID)
	var i GetOrganizationDeletionStateRow
	err := row.Scan(&i.Role, &i.HasProjects)
	return i, err
}

const listMembersForOrganization = `-- name: ListMembersForOrganization :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at,
       COALESCE(u.email, oi.provider_email) AS email
FROM organization_memberships om
JOIN organization_memberships requester
  ON requester.organization_id = om.organization_id
 AND requester.user_id = $1
JOIN users u ON u.id = om.user_id
LEFT JOIN LATERAL (
    SELECT provider_email
    FROM oauth_identities
    WHERE user_id = u.id AND provider_email IS NOT NULL
    ORDER BY created_at, provider, provider_user_id
    LIMIT 1
) oi ON TRUE
WHERE om.organization_id = $2
  AND u.deleted_at IS NULL
ORDER BY om.created_at, om.id
`

type ListMembersForOrganizationParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type ListMembersForOrganizationRow struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           OrganizationRole `json:"role"`
	CreatedAt      time.Time        `json:"created_at"`
	Email          sql.NullString   `json:"email"`
}

func (q *Queries) ListMembersForOrganization(ctx context.Context, arg ListMembersForOrganizationParams) ([]ListMembersForOrganizationRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersForOrganization, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersForOrganizationRow
	for rows.Next() {
		var i ListMembersForOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.created_at
FROM organizations o
JOIN organization_memberships om ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY o.created_at, o.id
`

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForOrganization = `-- name: ListProjectsForOrganization :many
WITH authorized AS (
    SELECT om.organization_id
    FROM organization_memberships om
    WHERE om.organization_id = $1
      AND om.user_id = $2
)
SELECT CASE WHEN p.id IS NULL THEN FALSE ELSE TRUE END AS has_project,
       COALESCE(p.id, '') AS id,
       COALESCE(p.name, '') AS name,
       COALESCE(p.created_at, TIMESTAMPTZ 'epoch') AS created_at,
       COALESCE(p.updated_at, TIMESTAMPTZ 'epoch') AS updated_at,
       a.organization_id
FROM authorized a
LEFT JOIN projects p
  ON p.organization_id = a.organization_id
 AND p.deleted_at IS NULL
ORDER BY p.created_at, p.id
`

type ListProjectsForOrganizationParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

type ListProjectsForOrganizationRow struct {
	HasProject     bool      `json:"has_project"`
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID string    `json:"organization_id"`
}

func (q *Queries) ListProjectsForOrganization(ctx context.Context, arg ListProjectsForOrganizationParams) ([]ListProjectsForOrganizationRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsForOrganization, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsForOrganizationRow
	for rows.Next() {
		var i ListProjectsForOrganizationRow
		if err := rows.Scan(
			&i.HasProject,
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations o
SET name = $1::text
WHERE o.id = $2
  AND EXISTS (
      SELECT 1
      FROM organization_memberships om
      WHERE om.organization_id = o.id
        AND om.user_id = $3
        AND om.role = 'owner'
  )
RETURNING id, name, slug, created_at
`

type UpdateOrganizationParams struct {
	Name           string `json:"name"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, updateOrganization, arg.Name, arg.OrganizationID, arg.UserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
