// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcdb

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, organization_id, name)
SELECT $1::text, $2::text, om.organization_id, $3::text
FROM organization_memberships om
WHERE om.organization_id = $4
  AND om.user_id = $2
RETURNING id, user_id, name, created_at, updated_at, deleted_at, organization_id
`

type CreateProjectParams struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	Name           string `json:"name"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.OrganizationID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT p.id, p.user_id, p.name, p.created_at, p.updated_at, p.deleted_at, p.organization_id
FROM projects p
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE p.id = $1 AND om.user_id = $2 AND p.deleted_at IS NULL
`

type GetProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getProjectMutationResource = `-- name: GetProjectMutationResource :one
SELECT p.id, om.role
FROM projects p
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE p.id = $1 AND om.user_id = $2
  AND p.deleted_at IS NULL
FOR UPDATE OF p
`

type GetProjectMutationResourceParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

type GetProjectMutationResourceRow struct {
	ID   string           `json:"id"`
	Role OrganizationRole `json:"role"`
}

func (q *Queries) GetProjectMutationResource(ctx context.Context, arg GetProjectMutationResourceParams) (GetProjectMutationResourceRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectMutationResource, arg.ProjectID, arg.UserID)
	var i GetProjectMutationResourceRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const listProjectIDsForHost = `-- name: ListProjectIDsForHost :many
SELECT DISTINCT p.id
FROM projects p
JOIN clusters c ON c.project_id = p.id
WHERE c.host_id = $1
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY p.id
`

func (q *Queries) ListProjectIDsForHost(ctx context.Context, hostID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectIDsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.user_id, p.name, p.created_at, p.updated_at, p.deleted_at, p.organization_id
FROM projects p
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE om.user_id = $1 AND p.deleted_at IS NULL
ORDER BY p.created_at, p.id
`

func (q *Queries) ListProjects(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :one
UPDATE projects p
SET deleted_at = NOW(), updated_at = NOW()
WHERE p.id = $1
  AND p.organization_id IN (
      SELECT om.organization_id FROM organization_memberships om WHERE om.user_id = $2
  )
  AND p.deleted_at IS NULL
RETURNING p.id
`

type SoftDeleteProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, softDeleteProject, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects p
SET name = $3, updated_at = NOW()
WHERE p.id = $1
  AND p.organization_id IN (
      SELECT om.organization_id FROM organization_memberships om WHERE om.user_id = $2
  )
  AND p.deleted_at IS NULL
RETURNING p.id, p.user_id, p.name, p.created_at, p.updated_at, p.deleted_at, p.organization_id
`

type UpdateProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.ID, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}
