// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcdb

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ID, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectIDsForHost = `-- name: ListProjectIDsForHost :many
SELECT DISTINCT p.id
FROM projects p
JOIN clusters c ON c.project_id = p.id
WHERE c.host_id = $1
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY p.id
`

func (q *Queries) ListProjectIDsForHost(ctx context.Context, hostID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectIDsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM projects
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :one
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, softDeleteProject, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.ID, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
