// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error)
	CreateDesiredState(ctx context.Context, arg CreateDesiredStateParams) (DesiredState, error)
	CreateHost(ctx context.Context, arg CreateHostParams) (Host, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateOAuthUser(ctx context.Context, id string) (string, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreatePasswordUser(ctx context.Context, arg CreatePasswordUserParams) (User, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) (int64, error)
	DeleteClusterReportsForHost(ctx context.Context, hostID string) error
	GetAgentReport(ctx context.Context, hostID string) (GetAgentReportRow, error)
	GetCluster(ctx context.Context, arg GetClusterParams) (Cluster, error)
	GetHostByTokenHash(ctx context.Context, tokenHash []byte) (Host, error)
	GetMembershipForUserAndOrg(ctx context.Context, arg GetMembershipForUserAndOrgParams) (OrganizationMembership, error)
	GetOAuthIdentityUserID(ctx context.Context, arg GetOAuthIdentityUserIDParams) (string, error)
	GetOrganizationByID(ctx context.Context, id string) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	ListActiveClustersForProject(ctx context.Context, arg ListActiveClustersForProjectParams) ([]Cluster, error)
	ListAlertIncidentsForProject(ctx context.Context, projectID string) ([]AlertIncident, error)
	ListAlertIncidentsForUser(ctx context.Context, userID string) ([]ListAlertIncidentsForUserRow, error)
	ListAlertRulesForEvaluation(ctx context.Context) ([]AlertRule, error)
	ListAlertRulesForProject(ctx context.Context, arg ListAlertRulesForProjectParams) ([]AlertRule, error)
	ListBackupJobs(ctx context.Context, arg ListBackupJobsParams) ([]ListBackupJobsRow, error)
	ListClusterReportsForHost(ctx context.Context, hostID string) ([]ClusterReport, error)
	ListClusters(ctx context.Context, arg ListClustersParams) ([]Cluster, error)
	ListCurrentDesiredStatesForHost(ctx context.Context, hostID string) ([]DesiredState, error)
	ListDesiredStateHistory(ctx context.Context, arg ListDesiredStateHistoryParams) ([]DesiredState, error)
	ListMembersForOrganization(ctx context.Context, organizationID string) ([]ListMembersForOrganizationRow, error)
	ListMetricClusterReports(ctx context.Context, projectID string) ([]ListMetricClusterReportsRow, error)
	ListOrganizationsForUser(ctx context.Context, userID string) ([]Organization, error)
	ListProjectHosts(ctx context.Context, arg ListProjectHostsParams) ([]Host, error)
	ListProjectIDsForHost(ctx context.Context, hostID string) ([]string, error)
	ListProjects(ctx context.Context, userID string) ([]Project, error)
	ListProjectsForOrganization(ctx context.Context, organizationID string) ([]Project, error)
	SoftDeleteCluster(ctx context.Context, arg SoftDeleteClusterParams) (SoftDeleteClusterRow, error)
	SoftDeleteClustersForProject(ctx context.Context, arg SoftDeleteClustersForProjectParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (string, error)
	SoftDeleteUser(ctx context.Context, id string) (string, error)
	UpdateAlertRuleState(ctx context.Context, arg UpdateAlertRuleStateParams) (UpdateAlertRuleStateRow, error)
	UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error)
	UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpsertAgentReport(ctx context.Context, arg UpsertAgentReportParams) error
	UpsertClusterReport(ctx context.Context, arg UpsertClusterReportParams) (int64, error)
	UserIsActive(ctx context.Context, id string) (bool, error)
}

var _ Querier = (*Queries)(nil)
