// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error)
	CreateDesiredState(ctx context.Context, arg CreateDesiredStateParams) (DesiredState, error)
	CreateHost(ctx context.Context, arg CreateHostParams) (Host, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteClusterReportsForHost(ctx context.Context, hostID string) error
	GetAgentReport(ctx context.Context, hostID string) (AgentReport, error)
	GetCluster(ctx context.Context, arg GetClusterParams) (Cluster, error)
	GetHostByTokenHash(ctx context.Context, tokenHash []byte) (Host, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	ListActiveClustersForProject(ctx context.Context, arg ListActiveClustersForProjectParams) ([]Cluster, error)
	ListClusterReportsForHost(ctx context.Context, hostID string) ([]ClusterReport, error)
	ListClusters(ctx context.Context, arg ListClustersParams) ([]Cluster, error)
	ListCurrentDesiredStatesForHost(ctx context.Context, hostID string) ([]DesiredState, error)
	ListDesiredStateHistory(ctx context.Context, arg ListDesiredStateHistoryParams) ([]DesiredState, error)
	ListProjects(ctx context.Context, userID string) ([]Project, error)
	SoftDeleteCluster(ctx context.Context, arg SoftDeleteClusterParams) (SoftDeleteClusterRow, error)
	SoftDeleteClustersForProject(ctx context.Context, arg SoftDeleteClustersForProjectParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (string, error)
	UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error)
	UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpsertAgentReport(ctx context.Context, arg UpsertAgentReportParams) error
	UpsertClusterReport(ctx context.Context, arg UpsertClusterReportParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
