// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const deleteClusterReportsForHost = `-- name: DeleteClusterReportsForHost :exec
DELETE FROM cluster_reports
WHERE host_id = $1
`

func (q *Queries) DeleteClusterReportsForHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, deleteClusterReportsForHost, hostID)
	return err
}

const getAgentReport = `-- name: GetAgentReport :one
SELECT host_id, actual_state, health_report, reported_at
FROM agent_reports
WHERE host_id = $1
`

func (q *Queries) GetAgentReport(ctx context.Context, hostID string) (AgentReport, error) {
	row := q.db.QueryRowContext(ctx, getAgentReport, hostID)
	var i AgentReport
	err := row.Scan(
		&i.HostID,
		&i.ActualState,
		&i.HealthReport,
		&i.ReportedAt,
	)
	return i, err
}

const listClusterReportsForHost = `-- name: ListClusterReportsForHost :many
SELECT host_id, cluster_id, actual_state, health_status, reported_at
FROM cluster_reports
WHERE host_id = $1
ORDER BY cluster_id
`

func (q *Queries) ListClusterReportsForHost(ctx context.Context, hostID string) ([]ClusterReport, error) {
	rows, err := q.db.QueryContext(ctx, listClusterReportsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClusterReport
	for rows.Next() {
		var i ClusterReport
		if err := rows.Scan(
			&i.HostID,
			&i.ClusterID,
			&i.ActualState,
			&i.HealthStatus,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentReport = `-- name: UpsertAgentReport :exec
INSERT INTO agent_reports (host_id, actual_state, health_report, reported_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (host_id) DO UPDATE
SET actual_state = EXCLUDED.actual_state,
    health_report = EXCLUDED.health_report,
    reported_at = EXCLUDED.reported_at
`

type UpsertAgentReportParams struct {
	HostID       string          `json:"host_id"`
	ActualState  json.RawMessage `json:"actual_state"`
	HealthReport json.RawMessage `json:"health_report"`
	ReportedAt   time.Time       `json:"reported_at"`
}

func (q *Queries) UpsertAgentReport(ctx context.Context, arg UpsertAgentReportParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentReport,
		arg.HostID,
		arg.ActualState,
		arg.HealthReport,
		arg.ReportedAt,
	)
	return err
}

const upsertClusterReport = `-- name: UpsertClusterReport :execrows
INSERT INTO cluster_reports (host_id, cluster_id, actual_state, health_status, reported_at)
SELECT $1, $2, $3, $4, $5
FROM clusters
WHERE id = $2 AND host_id = $1
ON CONFLICT (host_id, cluster_id) DO UPDATE
SET actual_state = EXCLUDED.actual_state,
    health_status = EXCLUDED.health_status,
    reported_at = EXCLUDED.reported_at
`

type UpsertClusterReportParams struct {
	HostID       string          `json:"host_id"`
	ClusterID    string          `json:"cluster_id"`
	ActualState  json.RawMessage `json:"actual_state"`
	HealthStatus string          `json:"health_status"`
	ReportedAt   time.Time       `json:"reported_at"`
}

func (q *Queries) UpsertClusterReport(ctx context.Context, arg UpsertClusterReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertClusterReport,
		arg.HostID,
		arg.ClusterID,
		arg.ActualState,
		arg.HealthStatus,
		arg.ReportedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
