// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const deleteClusterReportsForHost = `-- name: DeleteClusterReportsForHost :exec
DELETE FROM cluster_reports
WHERE host_id = $1
`

func (q *Queries) DeleteClusterReportsForHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, deleteClusterReportsForHost, hostID)
	return err
}

const getAgentReport = `-- name: GetAgentReport :one
SELECT host_id, actual_state, health_report, reconciliation_results, reported_at
FROM agent_reports
WHERE host_id = $1
`

type GetAgentReportRow struct {
	HostID                string          `json:"host_id"`
	ActualState           json.RawMessage `json:"actual_state"`
	HealthReport          json.RawMessage `json:"health_report"`
	ReconciliationResults json.RawMessage `json:"reconciliation_results"`
	ReportedAt            time.Time       `json:"reported_at"`
}

func (q *Queries) GetAgentReport(ctx context.Context, hostID string) (GetAgentReportRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentReport, hostID)
	var i GetAgentReportRow
	err := row.Scan(
		&i.HostID,
		&i.ActualState,
		&i.HealthReport,
		&i.ReconciliationResults,
		&i.ReportedAt,
	)
	return i, err
}

const listBackupJobs = `-- name: ListBackupJobs :many
SELECT p.id AS project_id, p.name AS project_name,
       c.id AS cluster_id, c.name AS cluster_name, c.pgbackrest_enabled,
       COALESCE(cr.actual_state, 'null'::jsonb) AS actual_state,
       COALESCE(cr.reported_at, 'epoch'::timestamptz) AS reported_at
FROM projects p
JOIN organization_memberships om ON om.organization_id = p.organization_id
JOIN clusters c ON c.project_id = p.id
LEFT JOIN cluster_reports cr ON cr.host_id = c.host_id AND cr.cluster_id = c.id
WHERE om.user_id = $1
  AND p.deleted_at IS NULL AND c.deleted_at IS NULL
  AND ($2::text = '' OR p.id = $2)
ORDER BY p.name, p.id, c.name, c.id
`

type ListBackupJobsParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

type ListBackupJobsRow struct {
	ProjectID         string          `json:"project_id"`
	ProjectName       string          `json:"project_name"`
	ClusterID         string          `json:"cluster_id"`
	ClusterName       string          `json:"cluster_name"`
	PgbackrestEnabled bool            `json:"pgbackrest_enabled"`
	ActualState       json.RawMessage `json:"actual_state"`
	ReportedAt        time.Time       `json:"reported_at"`
}

func (q *Queries) ListBackupJobs(ctx context.Context, arg ListBackupJobsParams) ([]ListBackupJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBackupJobs, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBackupJobsRow
	for rows.Next() {
		var i ListBackupJobsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.ClusterID,
			&i.ClusterName,
			&i.PgbackrestEnabled,
			&i.ActualState,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterReportsForHost = `-- name: ListClusterReportsForHost :many
SELECT host_id, cluster_id, actual_state, health_status, reported_at
FROM cluster_reports
WHERE host_id = $1
ORDER BY cluster_id
`

func (q *Queries) ListClusterReportsForHost(ctx context.Context, hostID string) ([]ClusterReport, error) {
	rows, err := q.db.QueryContext(ctx, listClusterReportsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClusterReport
	for rows.Next() {
		var i ClusterReport
		if err := rows.Scan(
			&i.HostID,
			&i.ClusterID,
			&i.ActualState,
			&i.HealthStatus,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricClusterReports = `-- name: ListMetricClusterReports :many
SELECT p.id AS project_id, c.id AS cluster_id,
       COALESCE(cr.actual_state, 'null'::jsonb) AS actual_state,
       COALESCE(cr.health_status, 'unknown') AS health_status,
       COALESCE(cr.reported_at, 'epoch'::timestamptz) AS reported_at
FROM projects p
JOIN clusters c ON c.project_id = p.id
LEFT JOIN cluster_reports cr ON cr.host_id = c.host_id AND cr.cluster_id = c.id
WHERE p.deleted_at IS NULL AND c.deleted_at IS NULL
  AND ($1::text = '' OR p.id = $1)
ORDER BY p.id, c.id
`

type ListMetricClusterReportsRow struct {
	ProjectID    string          `json:"project_id"`
	ClusterID    string          `json:"cluster_id"`
	ActualState  json.RawMessage `json:"actual_state"`
	HealthStatus string          `json:"health_status"`
	ReportedAt   time.Time       `json:"reported_at"`
}

func (q *Queries) ListMetricClusterReports(ctx context.Context, projectID string) ([]ListMetricClusterReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMetricClusterReports, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetricClusterReportsRow
	for rows.Next() {
		var i ListMetricClusterReportsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ClusterID,
			&i.ActualState,
			&i.HealthStatus,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentReport = `-- name: UpsertAgentReport :exec
INSERT INTO agent_reports (host_id, actual_state, health_report, reconciliation_results, reported_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (host_id) DO UPDATE
SET actual_state = EXCLUDED.actual_state,
    health_report = EXCLUDED.health_report,
    reconciliation_results = EXCLUDED.reconciliation_results,
    reported_at = EXCLUDED.reported_at
`

type UpsertAgentReportParams struct {
	HostID                string          `json:"host_id"`
	ActualState           json.RawMessage `json:"actual_state"`
	HealthReport          json.RawMessage `json:"health_report"`
	ReconciliationResults json.RawMessage `json:"reconciliation_results"`
	ReportedAt            time.Time       `json:"reported_at"`
}

func (q *Queries) UpsertAgentReport(ctx context.Context, arg UpsertAgentReportParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentReport,
		arg.HostID,
		arg.ActualState,
		arg.HealthReport,
		arg.ReconciliationResults,
		arg.ReportedAt,
	)
	return err
}

const upsertClusterReport = `-- name: UpsertClusterReport :execrows
INSERT INTO cluster_reports (host_id, cluster_id, actual_state, health_status, reported_at)
SELECT $1, $2, $3, $4, $5
FROM clusters
WHERE id = $2 AND host_id = $1
ON CONFLICT (host_id, cluster_id) DO UPDATE
SET actual_state = EXCLUDED.actual_state,
    health_status = EXCLUDED.health_status,
    reported_at = EXCLUDED.reported_at
`

type UpsertClusterReportParams struct {
	HostID       string          `json:"host_id"`
	ClusterID    string          `json:"cluster_id"`
	ActualState  json.RawMessage `json:"actual_state"`
	HealthStatus string          `json:"health_status"`
	ReportedAt   time.Time       `json:"reported_at"`
}

func (q *Queries) UpsertClusterReport(ctx context.Context, arg UpsertClusterReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertClusterReport,
		arg.HostID,
		arg.ClusterID,
		arg.ActualState,
		arg.HealthStatus,
		arg.ReportedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
