// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_operations.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const applyRestoreOperationReport = `-- name: ApplyRestoreOperationReport :one
UPDATE restore_operations
SET report_sequence = $1,
    status = $2::restore_operation_status,
    report = $3,
    finalized_at = CASE
        WHEN $2::restore_operation_status = 'finalized'::restore_operation_status THEN NOW()
        ELSE finalized_at
    END,
    updated_at = NOW()
WHERE id = $4 AND report_sequence < $1
RETURNING id, project_id, host_id, source_cluster_id, target_cluster_id, target_cluster_name, target_spec, mode, intent, status, target_time, request_fingerprint, idempotency_key, requested_by_user_id, report_sequence, report, created_at, updated_at, finalized_at
`

type ApplyRestoreOperationReportParams struct {
	ReportSequence int64                  `json:"report_sequence"`
	Status         RestoreOperationStatus `json:"status"`
	Report         json.RawMessage        `json:"report"`
	ID             string                 `json:"id"`
}

func (q *Queries) ApplyRestoreOperationReport(ctx context.Context, arg ApplyRestoreOperationReportParams) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, applyRestoreOperationReport,
		arg.ReportSequence,
		arg.Status,
		arg.Report,
		arg.ID,
	)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const createActivatedCloneCluster = `-- name: CreateActivatedCloneCluster :one
INSERT INTO clusters (
    id, project_id, host_id, name, postgres_version, parameters,
    replica_count, replica_ids, enabled_extensions, pgbouncer_enabled,
    pgbouncer_pool_mode, pgbouncer_max_connections, pgbouncer_publish_address,
    pgbouncer_publish_port, pgbackrest_enabled,
    pgbackrest_repo_path, pgbackrest_retention_full, pgbackrest_retention_diff,
    pgbackrest_full_interval_seconds, pgbackrest_diff_interval_seconds,
    pgbackrest_incr_interval_seconds, pg_hba_rules, restart_generation
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14,
    $15, $16,
    $17, $18,
    $19, $20,
    $21, $22,
    $23
)
RETURNING id, project_id, host_id, name, postgres_version, parameters, replica_count, pgbouncer_enabled, created_at, updated_at, deleted_at, pgbackrest_enabled, pgbackrest_repo_path, pgbackrest_retention_full, pgbackrest_retention_diff, pgbackrest_full_interval_seconds, pgbackrest_diff_interval_seconds, pgbackrest_incr_interval_seconds, replica_ids, enabled_extensions, pgbouncer_pool_mode, pgbouncer_max_connections, pg_hba_rules, restart_generation, pgbouncer_publish_address, pgbouncer_publish_port
`

type CreateActivatedCloneClusterParams struct {
	ID                            string          `json:"id"`
	ProjectID                     string          `json:"project_id"`
	HostID                        string          `json:"host_id"`
	Name                          string          `json:"name"`
	PostgresVersion               string          `json:"postgres_version"`
	Parameters                    json.RawMessage `json:"parameters"`
	ReplicaCount                  int32           `json:"replica_count"`
	ReplicaIds                    json.RawMessage `json:"replica_ids"`
	EnabledExtensions             json.RawMessage `json:"enabled_extensions"`
	PgbouncerEnabled              bool            `json:"pgbouncer_enabled"`
	PgbouncerPoolMode             string          `json:"pgbouncer_pool_mode"`
	PgbouncerMaxConnections       int32           `json:"pgbouncer_max_connections"`
	PgbouncerPublishAddress       string          `json:"pgbouncer_publish_address"`
	PgbouncerPublishPort          int32           `json:"pgbouncer_publish_port"`
	PgbackrestEnabled             bool            `json:"pgbackrest_enabled"`
	PgbackrestRepoPath            string          `json:"pgbackrest_repo_path"`
	PgbackrestRetentionFull       int32           `json:"pgbackrest_retention_full"`
	PgbackrestRetentionDiff       int32           `json:"pgbackrest_retention_diff"`
	PgbackrestFullIntervalSeconds int64           `json:"pgbackrest_full_interval_seconds"`
	PgbackrestDiffIntervalSeconds int64           `json:"pgbackrest_diff_interval_seconds"`
	PgbackrestIncrIntervalSeconds int64           `json:"pgbackrest_incr_interval_seconds"`
	PgHbaRules                    json.RawMessage `json:"pg_hba_rules"`
	RestartGeneration             int64           `json:"restart_generation"`
}

func (q *Queries) CreateActivatedCloneCluster(ctx context.Context, arg CreateActivatedCloneClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createActivatedCloneCluster,
		arg.ID,
		arg.ProjectID,
		arg.HostID,
		arg.Name,
		arg.PostgresVersion,
		arg.Parameters,
		arg.ReplicaCount,
		arg.ReplicaIds,
		arg.EnabledExtensions,
		arg.PgbouncerEnabled,
		arg.PgbouncerPoolMode,
		arg.PgbouncerMaxConnections,
		arg.PgbouncerPublishAddress,
		arg.PgbouncerPublishPort,
		arg.PgbackrestEnabled,
		arg.PgbackrestRepoPath,
		arg.PgbackrestRetentionFull,
		arg.PgbackrestRetentionDiff,
		arg.PgbackrestFullIntervalSeconds,
		arg.PgbackrestDiffIntervalSeconds,
		arg.PgbackrestIncrIntervalSeconds,
		arg.PgHbaRules,
		arg.RestartGeneration,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.PgbouncerEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PgbackrestEnabled,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgHbaRules,
		&i.RestartGeneration,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
	)
	return i, err
}

const createRestoreOperation = `-- name: CreateRestoreOperation :one
INSERT INTO restore_operations (
    id, project_id, host_id, source_cluster_id, target_cluster_id,
    target_cluster_name, target_spec, mode, target_time, request_fingerprint,
    idempotency_key, requested_by_user_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12
)
RETURNING id, project_id, host_id, source_cluster_id, target_cluster_id, target_cluster_name, target_spec, mode, intent, status, target_time, request_fingerprint, idempotency_key, requested_by_user_id, report_sequence, report, created_at, updated_at, finalized_at
`

type CreateRestoreOperationParams struct {
	ID                 string               `json:"id"`
	ProjectID          string               `json:"project_id"`
	HostID             string               `json:"host_id"`
	SourceClusterID    string               `json:"source_cluster_id"`
	TargetClusterID    sql.NullString       `json:"target_cluster_id"`
	TargetClusterName  sql.NullString       `json:"target_cluster_name"`
	TargetSpec         json.RawMessage      `json:"target_spec"`
	Mode               RestoreOperationMode `json:"mode"`
	TargetTime         time.Time            `json:"target_time"`
	RequestFingerprint string               `json:"request_fingerprint"`
	IdempotencyKey     string               `json:"idempotency_key"`
	RequestedByUserID  string               `json:"requested_by_user_id"`
}

func (q *Queries) CreateRestoreOperation(ctx context.Context, arg CreateRestoreOperationParams) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, createRestoreOperation,
		arg.ID,
		arg.ProjectID,
		arg.HostID,
		arg.SourceClusterID,
		arg.TargetClusterID,
		arg.TargetClusterName,
		arg.TargetSpec,
		arg.Mode,
		arg.TargetTime,
		arg.RequestFingerprint,
		arg.IdempotencyKey,
		arg.RequestedByUserID,
	)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const createRestoreOperationEvent = `-- name: CreateRestoreOperationEvent :one
INSERT INTO restore_operation_events (operation_id, host_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateRestoreOperationEventParams struct {
	OperationID string          `json:"operation_id"`
	HostID      string          `json:"host_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
}

func (q *Queries) CreateRestoreOperationEvent(ctx context.Context, arg CreateRestoreOperationEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRestoreOperationEvent,
		arg.OperationID,
		arg.HostID,
		arg.EventType,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findRestoreOperationByIdempotencyKey = `-- name: FindRestoreOperationByIdempotencyKey :one
SELECT ro.id, ro.project_id, ro.host_id, ro.source_cluster_id, ro.target_cluster_id, ro.target_cluster_name, ro.target_spec, ro.mode, ro.intent, ro.status, ro.target_time, ro.request_fingerprint, ro.idempotency_key, ro.requested_by_user_id, ro.report_sequence, ro.report, ro.created_at, ro.updated_at, ro.finalized_at
FROM restore_operations ro
JOIN projects p ON p.id = ro.project_id
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE ro.requested_by_user_id = $1
  AND ro.idempotency_key = $2
  AND om.user_id = $1
  AND om.role IN ('owner', 'admin')
`

type FindRestoreOperationByIdempotencyKeyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) FindRestoreOperationByIdempotencyKey(ctx context.Context, arg FindRestoreOperationByIdempotencyKeyParams) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, findRestoreOperationByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getRestoreMutationContext = `-- name: GetRestoreMutationContext :one
SELECT c.id AS source_cluster_id, c.project_id, c.host_id, c.pgbackrest_enabled,
       om.role, c.name, c.postgres_version, c.parameters, c.replica_count,
       c.replica_ids, c.enabled_extensions, c.pgbouncer_enabled,
       c.pgbouncer_pool_mode, c.pgbouncer_max_connections,
       c.pgbouncer_publish_address, c.pgbouncer_publish_port,
       c.pgbackrest_repo_path, c.pgbackrest_retention_full,
       c.pgbackrest_retention_diff, c.pgbackrest_full_interval_seconds,
       c.pgbackrest_diff_interval_seconds, c.pgbackrest_incr_interval_seconds,
       c.pg_hba_rules, c.restart_generation
FROM clusters c
JOIN projects p ON p.id = c.project_id AND p.deleted_at IS NULL
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE c.id = $1 AND om.user_id = $2
  AND c.deleted_at IS NULL
FOR UPDATE OF c
`

type GetRestoreMutationContextParams struct {
	SourceClusterID string `json:"source_cluster_id"`
	UserID          string `json:"user_id"`
}

type GetRestoreMutationContextRow struct {
	SourceClusterID               string           `json:"source_cluster_id"`
	ProjectID                     string           `json:"project_id"`
	HostID                        string           `json:"host_id"`
	PgbackrestEnabled             bool             `json:"pgbackrest_enabled"`
	Role                          OrganizationRole `json:"role"`
	Name                          string           `json:"name"`
	PostgresVersion               string           `json:"postgres_version"`
	Parameters                    json.RawMessage  `json:"parameters"`
	ReplicaCount                  int32            `json:"replica_count"`
	ReplicaIds                    json.RawMessage  `json:"replica_ids"`
	EnabledExtensions             json.RawMessage  `json:"enabled_extensions"`
	PgbouncerEnabled              bool             `json:"pgbouncer_enabled"`
	PgbouncerPoolMode             string           `json:"pgbouncer_pool_mode"`
	PgbouncerMaxConnections       int32            `json:"pgbouncer_max_connections"`
	PgbouncerPublishAddress       string           `json:"pgbouncer_publish_address"`
	PgbouncerPublishPort          int32            `json:"pgbouncer_publish_port"`
	PgbackrestRepoPath            string           `json:"pgbackrest_repo_path"`
	PgbackrestRetentionFull       int32            `json:"pgbackrest_retention_full"`
	PgbackrestRetentionDiff       int32            `json:"pgbackrest_retention_diff"`
	PgbackrestFullIntervalSeconds int64            `json:"pgbackrest_full_interval_seconds"`
	PgbackrestDiffIntervalSeconds int64            `json:"pgbackrest_diff_interval_seconds"`
	PgbackrestIncrIntervalSeconds int64            `json:"pgbackrest_incr_interval_seconds"`
	PgHbaRules                    json.RawMessage  `json:"pg_hba_rules"`
	RestartGeneration             int64            `json:"restart_generation"`
}

func (q *Queries) GetRestoreMutationContext(ctx context.Context, arg GetRestoreMutationContextParams) (GetRestoreMutationContextRow, error) {
	row := q.db.QueryRowContext(ctx, getRestoreMutationContext, arg.SourceClusterID, arg.UserID)
	var i GetRestoreMutationContextRow
	err := row.Scan(
		&i.SourceClusterID,
		&i.ProjectID,
		&i.HostID,
		&i.PgbackrestEnabled,
		&i.Role,
		&i.Name,
		&i.PostgresVersion,
		&i.Parameters,
		&i.ReplicaCount,
		&i.ReplicaIds,
		&i.EnabledExtensions,
		&i.PgbouncerEnabled,
		&i.PgbouncerPoolMode,
		&i.PgbouncerMaxConnections,
		&i.PgbouncerPublishAddress,
		&i.PgbouncerPublishPort,
		&i.PgbackrestRepoPath,
		&i.PgbackrestRetentionFull,
		&i.PgbackrestRetentionDiff,
		&i.PgbackrestFullIntervalSeconds,
		&i.PgbackrestDiffIntervalSeconds,
		&i.PgbackrestIncrIntervalSeconds,
		&i.PgHbaRules,
		&i.RestartGeneration,
	)
	return i, err
}

const getRestoreOperation = `-- name: GetRestoreOperation :one
SELECT ro.id, ro.project_id, ro.host_id, ro.source_cluster_id, ro.target_cluster_id, ro.target_cluster_name, ro.target_spec, ro.mode, ro.intent, ro.status, ro.target_time, ro.request_fingerprint, ro.idempotency_key, ro.requested_by_user_id, ro.report_sequence, ro.report, ro.created_at, ro.updated_at, ro.finalized_at
FROM restore_operations ro
JOIN projects p ON p.id = ro.project_id AND p.deleted_at IS NULL
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE ro.id = $1 AND om.user_id = $2
`

type GetRestoreOperationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRestoreOperation(ctx context.Context, arg GetRestoreOperationParams) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, getRestoreOperation, arg.ID, arg.UserID)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getRestoreOperationForUpdate = `-- name: GetRestoreOperationForUpdate :one
SELECT ro.id, ro.project_id, ro.host_id, ro.source_cluster_id, ro.target_cluster_id, ro.target_cluster_name, ro.target_spec, ro.mode, ro.intent, ro.status, ro.target_time, ro.request_fingerprint, ro.idempotency_key, ro.requested_by_user_id, ro.report_sequence, ro.report, ro.created_at, ro.updated_at, ro.finalized_at, om.role
FROM restore_operations ro
JOIN projects p ON p.id = ro.project_id AND p.deleted_at IS NULL
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE ro.id = $1 AND om.user_id = $2
FOR UPDATE OF ro
`

type GetRestoreOperationForUpdateParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetRestoreOperationForUpdateRow struct {
	RestoreOperation RestoreOperation `json:"restore_operation"`
	Role             OrganizationRole `json:"role"`
}

func (q *Queries) GetRestoreOperationForUpdate(ctx context.Context, arg GetRestoreOperationForUpdateParams) (GetRestoreOperationForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getRestoreOperationForUpdate, arg.ID, arg.UserID)
	var i GetRestoreOperationForUpdateRow
	err := row.Scan(
		&i.RestoreOperation.ID,
		&i.RestoreOperation.ProjectID,
		&i.RestoreOperation.HostID,
		&i.RestoreOperation.SourceClusterID,
		&i.RestoreOperation.TargetClusterID,
		&i.RestoreOperation.TargetClusterName,
		&i.RestoreOperation.TargetSpec,
		&i.RestoreOperation.Mode,
		&i.RestoreOperation.Intent,
		&i.RestoreOperation.Status,
		&i.RestoreOperation.TargetTime,
		&i.RestoreOperation.RequestFingerprint,
		&i.RestoreOperation.IdempotencyKey,
		&i.RestoreOperation.RequestedByUserID,
		&i.RestoreOperation.ReportSequence,
		&i.RestoreOperation.Report,
		&i.RestoreOperation.CreatedAt,
		&i.RestoreOperation.UpdatedAt,
		&i.RestoreOperation.FinalizedAt,
		&i.Role,
	)
	return i, err
}

const getRestoreRevisionForHost = `-- name: GetRestoreRevisionForHost :one
SELECT COALESCE(MAX(id), 0)::BIGINT
FROM restore_operation_events
WHERE host_id = $1
`

func (q *Queries) GetRestoreRevisionForHost(ctx context.Context, hostID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRestoreRevisionForHost, hostID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hasActiveRestoreConflict = `-- name: HasActiveRestoreConflict :one
SELECT EXISTS (
    SELECT 1 FROM restore_operations ro
    WHERE ro.status NOT IN ('cancelled', 'finalized')
      AND NOT (ro.mode = 'clone' AND ro.status = 'succeeded')
      AND (ro.source_cluster_id IN ($1, $2)
           OR ro.target_cluster_id IN ($1, $2))
)::boolean
`

type HasActiveRestoreConflictParams struct {
	SourceClusterID string         `json:"source_cluster_id"`
	TargetClusterID sql.NullString `json:"target_cluster_id"`
}

func (q *Queries) HasActiveRestoreConflict(ctx context.Context, arg HasActiveRestoreConflictParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveRestoreConflict, arg.SourceClusterID, arg.TargetClusterID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasClusterRestoreMutationConflict = `-- name: HasClusterRestoreMutationConflict :one
SELECT EXISTS (
    SELECT 1 FROM restore_operations ro
    WHERE ro.status NOT IN ('cancelled', 'finalized')
      AND (ro.source_cluster_id = $1
           OR ro.target_cluster_id = $1)
)::boolean
`

func (q *Queries) HasClusterRestoreMutationConflict(ctx context.Context, clusterID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasClusterRestoreMutationConflict, clusterID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasProjectRestoreMutationConflict = `-- name: HasProjectRestoreMutationConflict :one
SELECT EXISTS (
    SELECT 1
    FROM restore_operations ro
    WHERE ro.status NOT IN ('cancelled', 'finalized')
      AND EXISTS (
          SELECT 1
          FROM clusters c
          WHERE c.project_id = $1
            AND c.deleted_at IS NULL
            AND c.id IN (ro.source_cluster_id, ro.target_cluster_id)
      )
)::boolean
`

func (q *Queries) HasProjectRestoreMutationConflict(ctx context.Context, projectID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasProjectRestoreMutationConflict, projectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listActionableRestoreOperationsForHost = `-- name: ListActionableRestoreOperationsForHost :many
SELECT id, project_id, host_id, source_cluster_id, target_cluster_id, target_cluster_name, target_spec, mode, intent, status, target_time, request_fingerprint, idempotency_key, requested_by_user_id, report_sequence, report, created_at, updated_at, finalized_at FROM restore_operations
WHERE host_id = $1
  AND status NOT IN ('cancelled', 'finalized')
ORDER BY created_at, id
`

func (q *Queries) ListActionableRestoreOperationsForHost(ctx context.Context, hostID string) ([]RestoreOperation, error) {
	rows, err := q.db.QueryContext(ctx, listActionableRestoreOperationsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestoreOperation
	for rows.Next() {
		var i RestoreOperation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.SourceClusterID,
			&i.TargetClusterID,
			&i.TargetClusterName,
			&i.TargetSpec,
			&i.Mode,
			&i.Intent,
			&i.Status,
			&i.TargetTime,
			&i.RequestFingerprint,
			&i.IdempotencyKey,
			&i.RequestedByUserID,
			&i.ReportSequence,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestoreOperations = `-- name: ListRestoreOperations :many
SELECT ro.id, ro.project_id, ro.host_id, ro.source_cluster_id, ro.target_cluster_id, ro.target_cluster_name, ro.target_spec, ro.mode, ro.intent, ro.status, ro.target_time, ro.request_fingerprint, ro.idempotency_key, ro.requested_by_user_id, ro.report_sequence, ro.report, ro.created_at, ro.updated_at, ro.finalized_at
FROM restore_operations ro
JOIN projects p ON p.id = ro.project_id AND p.deleted_at IS NULL
JOIN organization_memberships om ON om.organization_id = p.organization_id
WHERE ro.project_id = $1 AND om.user_id = $2
ORDER BY ro.created_at DESC, ro.id
`

type ListRestoreOperationsParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListRestoreOperations(ctx context.Context, arg ListRestoreOperationsParams) ([]RestoreOperation, error) {
	rows, err := q.db.QueryContext(ctx, listRestoreOperations, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestoreOperation
	for rows.Next() {
		var i RestoreOperation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.SourceClusterID,
			&i.TargetClusterID,
			&i.TargetClusterName,
			&i.TargetSpec,
			&i.Mode,
			&i.Intent,
			&i.Status,
			&i.TargetTime,
			&i.RequestFingerprint,
			&i.IdempotencyKey,
			&i.RequestedByUserID,
			&i.ReportSequence,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRestoreOperationForAgentReport = `-- name: LockRestoreOperationForAgentReport :one
SELECT id, project_id, host_id, source_cluster_id, target_cluster_id, target_cluster_name, target_spec, mode, intent, status, target_time, request_fingerprint, idempotency_key, requested_by_user_id, report_sequence, report, created_at, updated_at, finalized_at FROM restore_operations
WHERE id = $1 AND host_id = $2
FOR UPDATE
`

type LockRestoreOperationForAgentReportParams struct {
	ID     string `json:"id"`
	HostID string `json:"host_id"`
}

func (q *Queries) LockRestoreOperationForAgentReport(ctx context.Context, arg LockRestoreOperationForAgentReportParams) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, lockRestoreOperationForAgentReport, arg.ID, arg.HostID)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const lockRestoreResource = `-- name: LockRestoreResource :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockRestoreResource(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, lockRestoreResource, resourceID)
	return err
}

const requestRestoreFinalization = `-- name: RequestRestoreFinalization :one
UPDATE restore_operations
SET intent = 'finalize',
    updated_at = NOW()
WHERE id = $1 AND status IN ('succeeded', 'rolled_back')
RETURNING id, project_id, host_id, source_cluster_id, target_cluster_id, target_cluster_name, target_spec, mode, intent, status, target_time, request_fingerprint, idempotency_key, requested_by_user_id, report_sequence, report, created_at, updated_at, finalized_at
`

func (q *Queries) RequestRestoreFinalization(ctx context.Context, id string) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, requestRestoreFinalization, id)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const updateRestoreIntent = `-- name: UpdateRestoreIntent :one
UPDATE restore_operations
SET intent = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, project_id, host_id, source_cluster_id, target_cluster_id, target_cluster_name, target_spec, mode, intent, status, target_time, request_fingerprint, idempotency_key, requested_by_user_id, report_sequence, report, created_at, updated_at, finalized_at
`

type UpdateRestoreIntentParams struct {
	Intent RestoreOperationIntent `json:"intent"`
	ID     string                 `json:"id"`
}

func (q *Queries) UpdateRestoreIntent(ctx context.Context, arg UpdateRestoreIntentParams) (RestoreOperation, error) {
	row := q.db.QueryRowContext(ctx, updateRestoreIntent, arg.Intent, arg.ID)
	var i RestoreOperation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.SourceClusterID,
		&i.TargetClusterID,
		&i.TargetClusterName,
		&i.TargetSpec,
		&i.Mode,
		&i.Intent,
		&i.Status,
		&i.TargetTime,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.RequestedByUserID,
		&i.ReportSequence,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}
