// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createPasswordUser = `-- name: CreatePasswordUser :one
INSERT INTO users (id, email, password_hash)
VALUES ($1, LOWER($2), $3)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreatePasswordUserParams struct {
	ID           string         `json:"id"`
	Lower        string         `json:"lower"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreatePasswordUser(ctx context.Context, arg CreatePasswordUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createPasswordUser, arg.ID, arg.Lower, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
