// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: orca.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterStatus is the health state reported for a cluster.
type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNSPECIFIED ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_PENDING     ClusterStatus = 1
	ClusterStatus_CLUSTER_STATUS_HEALTHY     ClusterStatus = 2
	ClusterStatus_CLUSTER_STATUS_DEGRADED    ClusterStatus = 3
	ClusterStatus_CLUSTER_STATUS_DOWN        ClusterStatus = 4
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_UNSPECIFIED",
		1: "CLUSTER_STATUS_PENDING",
		2: "CLUSTER_STATUS_HEALTHY",
		3: "CLUSTER_STATUS_DEGRADED",
		4: "CLUSTER_STATUS_DOWN",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_UNSPECIFIED": 0,
		"CLUSTER_STATUS_PENDING":     1,
		"CLUSTER_STATUS_HEALTHY":     2,
		"CLUSTER_STATUS_DEGRADED":    3,
		"CLUSTER_STATUS_DOWN":        4,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orca_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_orca_proto_enumTypes[0]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{0}
}

// DesiredStateMessage carries the complete current desired state from server to agent.
type DesiredStateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  *DesiredState          `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredStateMessage) Reset() {
	*x = DesiredStateMessage{}
	mi := &file_orca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredStateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredStateMessage) ProtoMessage() {}

func (x *DesiredStateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredStateMessage.ProtoReflect.Descriptor instead.
func (*DesiredStateMessage) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{0}
}

func (x *DesiredStateMessage) GetDesiredState() *DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return nil
}

// AgentReportMessage carries the agent's observed state and current health to the server.
type AgentReportMessage struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	ActualState             *ActualState              `protobuf:"bytes,1,opt,name=actual_state,json=actualState,proto3" json:"actual_state,omitempty"`
	HealthReport            *HealthReport             `protobuf:"bytes,2,opt,name=health_report,json=healthReport,proto3" json:"health_report,omitempty"`
	ReconciliationResults   []*ReconciliationResult   `protobuf:"bytes,3,rep,name=reconciliation_results,json=reconciliationResults,proto3" json:"reconciliation_results,omitempty"`
	DesiredStateRevision    string                    `protobuf:"bytes,4,opt,name=desired_state_revision,json=desiredStateRevision,proto3" json:"desired_state_revision,omitempty"`
	RestoreOperationReports []*RestoreOperationReport `protobuf:"bytes,5,rep,name=restore_operation_reports,json=restoreOperationReports,proto3" json:"restore_operation_reports,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AgentReportMessage) Reset() {
	*x = AgentReportMessage{}
	mi := &file_orca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReportMessage) ProtoMessage() {}

func (x *AgentReportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReportMessage.ProtoReflect.Descriptor instead.
func (*AgentReportMessage) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{1}
}

func (x *AgentReportMessage) GetActualState() *ActualState {
	if x != nil {
		return x.ActualState
	}
	return nil
}

func (x *AgentReportMessage) GetHealthReport() *HealthReport {
	if x != nil {
		return x.HealthReport
	}
	return nil
}

func (x *AgentReportMessage) GetReconciliationResults() []*ReconciliationResult {
	if x != nil {
		return x.ReconciliationResults
	}
	return nil
}

func (x *AgentReportMessage) GetDesiredStateRevision() string {
	if x != nil {
		return x.DesiredStateRevision
	}
	return ""
}

func (x *AgentReportMessage) GetRestoreOperationReports() []*RestoreOperationReport {
	if x != nil {
		return x.RestoreOperationReports
	}
	return nil
}

// ReconciliationResult describes the outcome of one agent action.
type ReconciliationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconciliationResult) Reset() {
	*x = ReconciliationResult{}
	mi := &file_orca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationResult) ProtoMessage() {}

func (x *ReconciliationResult) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationResult.ProtoReflect.Descriptor instead.
func (*ReconciliationResult) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{2}
}

func (x *ReconciliationResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ReconciliationResult) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ReconciliationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconciliationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReconciliationResult) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

// DesiredState is the desired set of clusters managed by the agent.
type DesiredState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Clusters          []*ClusterSpec         `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Revision          string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	RestoreOperations []*RestoreOperation    `protobuf:"bytes,4,rep,name=restore_operations,json=restoreOperations,proto3" json:"restore_operations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_orca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{3}
}

func (x *DesiredState) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DesiredState) GetClusters() []*ClusterSpec {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *DesiredState) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *DesiredState) GetRestoreOperations() []*RestoreOperation {
	if x != nil {
		return x.RestoreOperations
	}
	return nil
}

// RestoreOperation describes one durable host-level recovery intent.
type RestoreOperation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode               string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Intent             string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`
	SourceClusterId    string                 `protobuf:"bytes,4,opt,name=source_cluster_id,json=sourceClusterId,proto3" json:"source_cluster_id,omitempty"`
	TargetCluster      *ClusterSpec           `protobuf:"bytes,5,opt,name=target_cluster,json=targetCluster,proto3,oneof" json:"target_cluster,omitempty"`
	TargetTime         string                 `protobuf:"bytes,6,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	RequestFingerprint string                 `protobuf:"bytes,7,opt,name=request_fingerprint,json=requestFingerprint,proto3" json:"request_fingerprint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RestoreOperation) Reset() {
	*x = RestoreOperation{}
	mi := &file_orca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreOperation) ProtoMessage() {}

func (x *RestoreOperation) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreOperation.ProtoReflect.Descriptor instead.
func (*RestoreOperation) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreOperation) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RestoreOperation) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *RestoreOperation) GetSourceClusterId() string {
	if x != nil {
		return x.SourceClusterId
	}
	return ""
}

func (x *RestoreOperation) GetTargetCluster() *ClusterSpec {
	if x != nil {
		return x.TargetCluster
	}
	return nil
}

func (x *RestoreOperation) GetTargetTime() string {
	if x != nil {
		return x.TargetTime
	}
	return ""
}

func (x *RestoreOperation) GetRequestFingerprint() string {
	if x != nil {
		return x.RequestFingerprint
	}
	return ""
}

// RestoreOperationReport describes the agent's durable recovery progress.
type RestoreOperationReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OperationId        string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Sequence           uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Phase              string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	DestructiveStarted bool                   `protobuf:"varint,7,opt,name=destructive_started,json=destructiveStarted,proto3" json:"destructive_started,omitempty"`
	Cancellable        bool                   `protobuf:"varint,8,opt,name=cancellable,proto3" json:"cancellable,omitempty"`
	RollbackAvailable  bool                   `protobuf:"varint,9,opt,name=rollback_available,json=rollbackAvailable,proto3" json:"rollback_available,omitempty"`
	BackupLabel        string                 `protobuf:"bytes,10,opt,name=backup_label,json=backupLabel,proto3" json:"backup_label,omitempty"`
	RecoveryEarliest   string                 `protobuf:"bytes,11,opt,name=recovery_earliest,json=recoveryEarliest,proto3" json:"recovery_earliest,omitempty"`
	RecoveryLatest     string                 `protobuf:"bytes,12,opt,name=recovery_latest,json=recoveryLatest,proto3" json:"recovery_latest,omitempty"`
	PostgresVersion    string                 `protobuf:"bytes,13,opt,name=postgres_version,json=postgresVersion,proto3" json:"postgres_version,omitempty"`
	RequiredBytes      uint64                 `protobuf:"varint,14,opt,name=required_bytes,json=requiredBytes,proto3" json:"required_bytes,omitempty"`
	AvailableBytes     uint64                 `protobuf:"varint,15,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	StartedAt          string                 `protobuf:"bytes,16,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,17,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RestoreOperationReport) Reset() {
	*x = RestoreOperationReport{}
	mi := &file_orca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreOperationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreOperationReport) ProtoMessage() {}

func (x *RestoreOperationReport) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreOperationReport.ProtoReflect.Descriptor instead.
func (*RestoreOperationReport) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreOperationReport) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RestoreOperationReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RestoreOperationReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RestoreOperationReport) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RestoreOperationReport) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RestoreOperationReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RestoreOperationReport) GetDestructiveStarted() bool {
	if x != nil {
		return x.DestructiveStarted
	}
	return false
}

func (x *RestoreOperationReport) GetCancellable() bool {
	if x != nil {
		return x.Cancellable
	}
	return false
}

func (x *RestoreOperationReport) GetRollbackAvailable() bool {
	if x != nil {
		return x.RollbackAvailable
	}
	return false
}

func (x *RestoreOperationReport) GetBackupLabel() string {
	if x != nil {
		return x.BackupLabel
	}
	return ""
}

func (x *RestoreOperationReport) GetRecoveryEarliest() string {
	if x != nil {
		return x.RecoveryEarliest
	}
	return ""
}

func (x *RestoreOperationReport) GetRecoveryLatest() string {
	if x != nil {
		return x.RecoveryLatest
	}
	return ""
}

func (x *RestoreOperationReport) GetPostgresVersion() string {
	if x != nil {
		return x.PostgresVersion
	}
	return ""
}

func (x *RestoreOperationReport) GetRequiredBytes() uint64 {
	if x != nil {
		return x.RequiredBytes
	}
	return 0
}

func (x *RestoreOperationReport) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *RestoreOperationReport) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RestoreOperationReport) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

// ClusterSpec describes a desired Postgres cluster.
type ClusterSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Params            map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Replicas          []*ReplicaSpec         `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty"`
	PgBouncer         *PgBouncerSpec         `protobuf:"bytes,5,opt,name=pg_bouncer,json=pgBouncer,proto3,oneof" json:"pg_bouncer,omitempty"`
	Databases         []*DatabaseSpec        `protobuf:"bytes,6,rep,name=databases,proto3" json:"databases,omitempty"`
	PgBackRest        *PgBackRestSpec        `protobuf:"bytes,7,opt,name=pg_back_rest,json=pgBackRest,proto3,oneof" json:"pg_back_rest,omitempty"`
	EnabledExtensions []string               `protobuf:"bytes,8,rep,name=enabled_extensions,json=enabledExtensions,proto3" json:"enabled_extensions,omitempty"`
	PgHba             *PgHbaSpec             `protobuf:"bytes,9,opt,name=pg_hba,json=pgHba,proto3,oneof" json:"pg_hba,omitempty"`
	RestartGeneration uint64                 `protobuf:"varint,10,opt,name=restart_generation,json=restartGeneration,proto3" json:"restart_generation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClusterSpec) Reset() {
	*x = ClusterSpec{}
	mi := &file_orca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSpec) ProtoMessage() {}

func (x *ClusterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSpec.ProtoReflect.Descriptor instead.
func (*ClusterSpec) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterSpec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ClusterSpec) GetReplicas() []*ReplicaSpec {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *ClusterSpec) GetPgBouncer() *PgBouncerSpec {
	if x != nil {
		return x.PgBouncer
	}
	return nil
}

func (x *ClusterSpec) GetDatabases() []*DatabaseSpec {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *ClusterSpec) GetPgBackRest() *PgBackRestSpec {
	if x != nil {
		return x.PgBackRest
	}
	return nil
}

func (x *ClusterSpec) GetEnabledExtensions() []string {
	if x != nil {
		return x.EnabledExtensions
	}
	return nil
}

func (x *ClusterSpec) GetPgHba() *PgHbaSpec {
	if x != nil {
		return x.PgHba
	}
	return nil
}

func (x *ClusterSpec) GetRestartGeneration() uint64 {
	if x != nil {
		return x.RestartGeneration
	}
	return 0
}

// PgHbaSpec contains an ordered PostgreSQL client authentication policy.
type PgHbaSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PgHbaRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgHbaSpec) Reset() {
	*x = PgHbaSpec{}
	mi := &file_orca_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgHbaSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgHbaSpec) ProtoMessage() {}

func (x *PgHbaSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgHbaSpec.ProtoReflect.Descriptor instead.
func (*PgHbaSpec) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{7}
}

func (x *PgHbaSpec) GetRules() []*PgHbaRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// PgHbaRule describes one ordered PostgreSQL client authentication rule.
type PgHbaRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgHbaRule) Reset() {
	*x = PgHbaRule{}
	mi := &file_orca_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgHbaRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgHbaRule) ProtoMessage() {}

func (x *PgHbaRule) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgHbaRule.ProtoReflect.Descriptor instead.
func (*PgHbaRule) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{8}
}

func (x *PgHbaRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PgHbaRule) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PgHbaRule) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PgHbaRule) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PgHbaRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// ReplicaSpec describes a desired Postgres replica.
type ReplicaSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaSpec) Reset() {
	*x = ReplicaSpec{}
	mi := &file_orca_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSpec) ProtoMessage() {}

func (x *ReplicaSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSpec.ProtoReflect.Descriptor instead.
func (*ReplicaSpec) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicaSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DatabaseSpec describes a desired Postgres database.
type DatabaseSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseSpec) Reset() {
	*x = DatabaseSpec{}
	mi := &file_orca_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseSpec) ProtoMessage() {}

func (x *DatabaseSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseSpec.ProtoReflect.Descriptor instead.
func (*DatabaseSpec) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{10}
}

func (x *DatabaseSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PgBouncerSpec describes a desired PgBouncer sidecar.
type PgBouncerSpec struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PoolMode                  string                 `protobuf:"bytes,1,opt,name=pool_mode,json=poolMode,proto3" json:"pool_mode,omitempty"`
	MaxConnections            uint32                 `protobuf:"varint,2,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	ReservePoolSize           uint32                 `protobuf:"varint,3,opt,name=reserve_pool_size,json=reservePoolSize,proto3" json:"reserve_pool_size,omitempty"`
	ReservePoolTimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=reserve_pool_timeout_seconds,json=reservePoolTimeoutSeconds,proto3" json:"reserve_pool_timeout_seconds,omitempty"`
	PublishAddress            string                 `protobuf:"bytes,5,opt,name=publish_address,json=publishAddress,proto3" json:"publish_address,omitempty"`
	PublishPort               uint32                 `protobuf:"varint,6,opt,name=publish_port,json=publishPort,proto3" json:"publish_port,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PgBouncerSpec) Reset() {
	*x = PgBouncerSpec{}
	mi := &file_orca_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgBouncerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgBouncerSpec) ProtoMessage() {}

func (x *PgBouncerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgBouncerSpec.ProtoReflect.Descriptor instead.
func (*PgBouncerSpec) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{11}
}

func (x *PgBouncerSpec) GetPoolMode() string {
	if x != nil {
		return x.PoolMode
	}
	return ""
}

func (x *PgBouncerSpec) GetMaxConnections() uint32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *PgBouncerSpec) GetReservePoolSize() uint32 {
	if x != nil {
		return x.ReservePoolSize
	}
	return 0
}

func (x *PgBouncerSpec) GetReservePoolTimeoutSeconds() uint32 {
	if x != nil {
		return x.ReservePoolTimeoutSeconds
	}
	return 0
}

func (x *PgBouncerSpec) GetPublishAddress() string {
	if x != nil {
		return x.PublishAddress
	}
	return ""
}

func (x *PgBouncerSpec) GetPublishPort() uint32 {
	if x != nil {
		return x.PublishPort
	}
	return 0
}

// PgBackRestSpec describes the desired backup repository and retention policy.
type PgBackRestSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	RetentionFull uint32                 `protobuf:"varint,2,opt,name=retention_full,json=retentionFull,proto3" json:"retention_full,omitempty"`
	RetentionDiff uint32                 `protobuf:"varint,3,opt,name=retention_diff,json=retentionDiff,proto3" json:"retention_diff,omitempty"`
	Schedule      *BackupSchedule        `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgBackRestSpec) Reset() {
	*x = PgBackRestSpec{}
	mi := &file_orca_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgBackRestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgBackRestSpec) ProtoMessage() {}

func (x *PgBackRestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgBackRestSpec.ProtoReflect.Descriptor instead.
func (*PgBackRestSpec) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{12}
}

func (x *PgBackRestSpec) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PgBackRestSpec) GetRetentionFull() uint32 {
	if x != nil {
		return x.RetentionFull
	}
	return 0
}

func (x *PgBackRestSpec) GetRetentionDiff() uint32 {
	if x != nil {
		return x.RetentionDiff
	}
	return 0
}

func (x *PgBackRestSpec) GetSchedule() *BackupSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// BackupSchedule describes interval-based backup scheduling.
type BackupSchedule struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FullIntervalSeconds uint64                 `protobuf:"varint,1,opt,name=full_interval_seconds,json=fullIntervalSeconds,proto3" json:"full_interval_seconds,omitempty"`
	DiffIntervalSeconds uint64                 `protobuf:"varint,2,opt,name=diff_interval_seconds,json=diffIntervalSeconds,proto3" json:"diff_interval_seconds,omitempty"`
	IncrIntervalSeconds uint64                 `protobuf:"varint,3,opt,name=incr_interval_seconds,json=incrIntervalSeconds,proto3" json:"incr_interval_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupSchedule) Reset() {
	*x = BackupSchedule{}
	mi := &file_orca_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSchedule) ProtoMessage() {}

func (x *BackupSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSchedule.ProtoReflect.Descriptor instead.
func (*BackupSchedule) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{13}
}

func (x *BackupSchedule) GetFullIntervalSeconds() uint64 {
	if x != nil {
		return x.FullIntervalSeconds
	}
	return 0
}

func (x *BackupSchedule) GetDiffIntervalSeconds() uint64 {
	if x != nil {
		return x.DiffIntervalSeconds
	}
	return 0
}

func (x *BackupSchedule) GetIncrIntervalSeconds() uint64 {
	if x != nil {
		return x.IncrIntervalSeconds
	}
	return 0
}

// ActualState is the set of clusters currently observed by the agent.
type ActualState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ActualCluster       `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualState) Reset() {
	*x = ActualState{}
	mi := &file_orca_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualState) ProtoMessage() {}

func (x *ActualState) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualState.ProtoReflect.Descriptor instead.
func (*ActualState) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{14}
}

func (x *ActualState) GetClusters() []*ActualCluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

// ActualCluster describes an observed Postgres primary and its child resources.
type ActualCluster struct {
	state                    protoimpl.MessageState             `protogen:"open.v1"`
	Id                       string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContainerId              string                             `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status                   string                             `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Version                  string                             `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Replicas                 []*ActualReplica                   `protobuf:"bytes,5,rep,name=replicas,proto3" json:"replicas,omitempty"`
	PgBouncer                *ActualPgBouncer                   `protobuf:"bytes,6,opt,name=pg_bouncer,json=pgBouncer,proto3,oneof" json:"pg_bouncer,omitempty"`
	Backup                   *ActualBackup                      `protobuf:"bytes,7,opt,name=backup,proto3,oneof" json:"backup,omitempty"`
	EnabledExtensions        []string                           `protobuf:"bytes,8,rep,name=enabled_extensions,json=enabledExtensions,proto3" json:"enabled_extensions,omitempty"`
	AppliedParams            map[string]string                  `protobuf:"bytes,9,rep,name=applied_params,json=appliedParams,proto3" json:"applied_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VolumeExists             bool                               `protobuf:"varint,10,opt,name=volume_exists,json=volumeExists,proto3" json:"volume_exists,omitempty"`
	Image                    string                             `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	PostgresReady            *bool                              `protobuf:"varint,12,opt,name=postgres_ready,json=postgresReady,proto3,oneof" json:"postgres_ready,omitempty"`
	ExtensionVersions        map[string]string                  `protobuf:"bytes,13,rep,name=extension_versions,json=extensionVersions,proto3" json:"extension_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExtensionUpdateMethods   map[string]string                  `protobuf:"bytes,14,rep,name=extension_update_methods,json=extensionUpdateMethods,proto3" json:"extension_update_methods,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PgHbaRules               []*PgHbaRule                       `protobuf:"bytes,15,rep,name=pg_hba_rules,json=pgHbaRules,proto3" json:"pg_hba_rules,omitempty"`
	PgHbaObserved            bool                               `protobuf:"varint,16,opt,name=pg_hba_observed,json=pgHbaObserved,proto3" json:"pg_hba_observed,omitempty"`
	NetworkCidrs             []string                           `protobuf:"bytes,17,rep,name=network_cidrs,json=networkCidrs,proto3" json:"network_cidrs,omitempty"`
	PgHbaReplicationCidrs    []string                           `protobuf:"bytes,18,rep,name=pg_hba_replication_cidrs,json=pgHbaReplicationCidrs,proto3" json:"pg_hba_replication_cidrs,omitempty"`
	ParameterStates          map[string]*PostgresParameterState `protobuf:"bytes,19,rep,name=parameter_states,json=parameterStates,proto3" json:"parameter_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParametersObserved       bool                               `protobuf:"varint,20,opt,name=parameters_observed,json=parametersObserved,proto3" json:"parameters_observed,omitempty"`
	AppliedRestartGeneration uint64                             `protobuf:"varint,21,opt,name=applied_restart_generation,json=appliedRestartGeneration,proto3" json:"applied_restart_generation,omitempty"`
	NetworkName              string                             `protobuf:"bytes,22,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	PgHbaPoolCidrs           []string                           `protobuf:"bytes,23,rep,name=pg_hba_pool_cidrs,json=pgHbaPoolCidrs,proto3" json:"pg_hba_pool_cidrs,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ActualCluster) Reset() {
	*x = ActualCluster{}
	mi := &file_orca_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualCluster) ProtoMessage() {}

func (x *ActualCluster) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualCluster.ProtoReflect.Descriptor instead.
func (*ActualCluster) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{15}
}

func (x *ActualCluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualCluster) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ActualCluster) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActualCluster) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ActualCluster) GetReplicas() []*ActualReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *ActualCluster) GetPgBouncer() *ActualPgBouncer {
	if x != nil {
		return x.PgBouncer
	}
	return nil
}

func (x *ActualCluster) GetBackup() *ActualBackup {
	if x != nil {
		return x.Backup
	}
	return nil
}

func (x *ActualCluster) GetEnabledExtensions() []string {
	if x != nil {
		return x.EnabledExtensions
	}
	return nil
}

func (x *ActualCluster) GetAppliedParams() map[string]string {
	if x != nil {
		return x.AppliedParams
	}
	return nil
}

func (x *ActualCluster) GetVolumeExists() bool {
	if x != nil {
		return x.VolumeExists
	}
	return false
}

func (x *ActualCluster) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ActualCluster) GetPostgresReady() bool {
	if x != nil && x.PostgresReady != nil {
		return *x.PostgresReady
	}
	return false
}

func (x *ActualCluster) GetExtensionVersions() map[string]string {
	if x != nil {
		return x.ExtensionVersions
	}
	return nil
}

func (x *ActualCluster) GetExtensionUpdateMethods() map[string]string {
	if x != nil {
		return x.ExtensionUpdateMethods
	}
	return nil
}

func (x *ActualCluster) GetPgHbaRules() []*PgHbaRule {
	if x != nil {
		return x.PgHbaRules
	}
	return nil
}

func (x *ActualCluster) GetPgHbaObserved() bool {
	if x != nil {
		return x.PgHbaObserved
	}
	return false
}

func (x *ActualCluster) GetNetworkCidrs() []string {
	if x != nil {
		return x.NetworkCidrs
	}
	return nil
}

func (x *ActualCluster) GetPgHbaReplicationCidrs() []string {
	if x != nil {
		return x.PgHbaReplicationCidrs
	}
	return nil
}

func (x *ActualCluster) GetParameterStates() map[string]*PostgresParameterState {
	if x != nil {
		return x.ParameterStates
	}
	return nil
}

func (x *ActualCluster) GetParametersObserved() bool {
	if x != nil {
		return x.ParametersObserved
	}
	return false
}

func (x *ActualCluster) GetAppliedRestartGeneration() uint64 {
	if x != nil {
		return x.AppliedRestartGeneration
	}
	return 0
}

func (x *ActualCluster) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *ActualCluster) GetPgHbaPoolCidrs() []string {
	if x != nil {
		return x.PgHbaPoolCidrs
	}
	return nil
}

// PostgresParameterState describes PostgreSQL's live view of one managed parameter.
type PostgresParameterState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Setting        string                 `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	Unit           string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Context        string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	UpdateMethod   string                 `protobuf:"bytes,4,opt,name=update_method,json=updateMethod,proto3" json:"update_method,omitempty"`
	PendingRestart bool                   `protobuf:"varint,5,opt,name=pending_restart,json=pendingRestart,proto3" json:"pending_restart,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Applied        bool                   `protobuf:"varint,7,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostgresParameterState) Reset() {
	*x = PostgresParameterState{}
	mi := &file_orca_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresParameterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresParameterState) ProtoMessage() {}

func (x *PostgresParameterState) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresParameterState.ProtoReflect.Descriptor instead.
func (*PostgresParameterState) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{16}
}

func (x *PostgresParameterState) GetSetting() string {
	if x != nil {
		return x.Setting
	}
	return ""
}

func (x *PostgresParameterState) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *PostgresParameterState) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *PostgresParameterState) GetUpdateMethod() string {
	if x != nil {
		return x.UpdateMethod
	}
	return ""
}

func (x *PostgresParameterState) GetPendingRestart() bool {
	if x != nil {
		return x.PendingRestart
	}
	return false
}

func (x *PostgresParameterState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PostgresParameterState) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

// ActualReplica describes an observed Postgres replica.
type ActualReplica struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContainerId          string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status               string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ReplicationLagBytes  *uint64                `protobuf:"varint,4,opt,name=replication_lag_bytes,json=replicationLagBytes,proto3,oneof" json:"replication_lag_bytes,omitempty"`
	StandbyConnected     *bool                  `protobuf:"varint,5,opt,name=standby_connected,json=standbyConnected,proto3,oneof" json:"standby_connected,omitempty"`
	StreamingState       string                 `protobuf:"bytes,6,opt,name=streaming_state,json=streamingState,proto3" json:"streaming_state,omitempty"`
	LastWalReceivedLsn   string                 `protobuf:"bytes,7,opt,name=last_wal_received_lsn,json=lastWalReceivedLsn,proto3" json:"last_wal_received_lsn,omitempty"`
	LastWalReplayedLsn   string                 `protobuf:"bytes,8,opt,name=last_wal_replayed_lsn,json=lastWalReplayedLsn,proto3" json:"last_wal_replayed_lsn,omitempty"`
	ReplicationLagStatus string                 `protobuf:"bytes,9,opt,name=replication_lag_status,json=replicationLagStatus,proto3" json:"replication_lag_status,omitempty"`
	PgHbaRules           []*PgHbaRule           `protobuf:"bytes,10,rep,name=pg_hba_rules,json=pgHbaRules,proto3" json:"pg_hba_rules,omitempty"`
	PgHbaObserved        bool                   `protobuf:"varint,11,opt,name=pg_hba_observed,json=pgHbaObserved,proto3" json:"pg_hba_observed,omitempty"`
	AppliedParams        map[string]string      `protobuf:"bytes,12,rep,name=applied_params,json=appliedParams,proto3" json:"applied_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParametersObserved   bool                   `protobuf:"varint,13,opt,name=parameters_observed,json=parametersObserved,proto3" json:"parameters_observed,omitempty"`
	NetworkName          string                 `protobuf:"bytes,14,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	PgHbaPoolCidrs       []string               `protobuf:"bytes,15,rep,name=pg_hba_pool_cidrs,json=pgHbaPoolCidrs,proto3" json:"pg_hba_pool_cidrs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActualReplica) Reset() {
	*x = ActualReplica{}
	mi := &file_orca_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualReplica) ProtoMessage() {}

func (x *ActualReplica) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualReplica.ProtoReflect.Descriptor instead.
func (*ActualReplica) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{17}
}

func (x *ActualReplica) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualReplica) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ActualReplica) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActualReplica) GetReplicationLagBytes() uint64 {
	if x != nil && x.ReplicationLagBytes != nil {
		return *x.ReplicationLagBytes
	}
	return 0
}

func (x *ActualReplica) GetStandbyConnected() bool {
	if x != nil && x.StandbyConnected != nil {
		return *x.StandbyConnected
	}
	return false
}

func (x *ActualReplica) GetStreamingState() string {
	if x != nil {
		return x.StreamingState
	}
	return ""
}

func (x *ActualReplica) GetLastWalReceivedLsn() string {
	if x != nil {
		return x.LastWalReceivedLsn
	}
	return ""
}

func (x *ActualReplica) GetLastWalReplayedLsn() string {
	if x != nil {
		return x.LastWalReplayedLsn
	}
	return ""
}

func (x *ActualReplica) GetReplicationLagStatus() string {
	if x != nil {
		return x.ReplicationLagStatus
	}
	return ""
}

func (x *ActualReplica) GetPgHbaRules() []*PgHbaRule {
	if x != nil {
		return x.PgHbaRules
	}
	return nil
}

func (x *ActualReplica) GetPgHbaObserved() bool {
	if x != nil {
		return x.PgHbaObserved
	}
	return false
}

func (x *ActualReplica) GetAppliedParams() map[string]string {
	if x != nil {
		return x.AppliedParams
	}
	return nil
}

func (x *ActualReplica) GetParametersObserved() bool {
	if x != nil {
		return x.ParametersObserved
	}
	return false
}

func (x *ActualReplica) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *ActualReplica) GetPgHbaPoolCidrs() []string {
	if x != nil {
		return x.PgHbaPoolCidrs
	}
	return nil
}

// ActualPgBouncer describes an observed PgBouncer sidecar.
type ActualPgBouncer struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ContainerId             string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status                  string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Config                  string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	ActiveClientConnections *uint32                `protobuf:"varint,4,opt,name=active_client_connections,json=activeClientConnections,proto3,oneof" json:"active_client_connections,omitempty"`
	MaxClientConnections    *uint32                `protobuf:"varint,5,opt,name=max_client_connections,json=maxClientConnections,proto3,oneof" json:"max_client_connections,omitempty"`
	AdminConsoleReachable   *bool                  `protobuf:"varint,6,opt,name=admin_console_reachable,json=adminConsoleReachable,proto3,oneof" json:"admin_console_reachable,omitempty"`
	NetworkName             string                 `protobuf:"bytes,7,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	PublishedAddress        string                 `protobuf:"bytes,8,opt,name=published_address,json=publishedAddress,proto3" json:"published_address,omitempty"`
	PublishedPort           uint32                 `protobuf:"varint,9,opt,name=published_port,json=publishedPort,proto3" json:"published_port,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActualPgBouncer) Reset() {
	*x = ActualPgBouncer{}
	mi := &file_orca_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualPgBouncer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualPgBouncer) ProtoMessage() {}

func (x *ActualPgBouncer) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualPgBouncer.ProtoReflect.Descriptor instead.
func (*ActualPgBouncer) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{18}
}

func (x *ActualPgBouncer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ActualPgBouncer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActualPgBouncer) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ActualPgBouncer) GetActiveClientConnections() uint32 {
	if x != nil && x.ActiveClientConnections != nil {
		return *x.ActiveClientConnections
	}
	return 0
}

func (x *ActualPgBouncer) GetMaxClientConnections() uint32 {
	if x != nil && x.MaxClientConnections != nil {
		return *x.MaxClientConnections
	}
	return 0
}

func (x *ActualPgBouncer) GetAdminConsoleReachable() bool {
	if x != nil && x.AdminConsoleReachable != nil {
		return *x.AdminConsoleReachable
	}
	return false
}

func (x *ActualPgBouncer) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *ActualPgBouncer) GetPublishedAddress() string {
	if x != nil {
		return x.PublishedAddress
	}
	return ""
}

func (x *ActualPgBouncer) GetPublishedPort() uint32 {
	if x != nil {
		return x.PublishedPort
	}
	return 0
}

// ActualBackup describes applied backup configuration and the latest observed success.
type ActualBackup struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LastSuccessUnixSeconds *int64                 `protobuf:"varint,1,opt,name=last_success_unix_seconds,json=lastSuccessUnixSeconds,proto3,oneof" json:"last_success_unix_seconds,omitempty"`
	Config                 string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	SizeBytes              *uint64                `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3,oneof" json:"size_bytes,omitempty"`
	Status                 string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ActualBackup) Reset() {
	*x = ActualBackup{}
	mi := &file_orca_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualBackup) ProtoMessage() {}

func (x *ActualBackup) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualBackup.ProtoReflect.Descriptor instead.
func (*ActualBackup) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{19}
}

func (x *ActualBackup) GetLastSuccessUnixSeconds() int64 {
	if x != nil && x.LastSuccessUnixSeconds != nil {
		return *x.LastSuccessUnixSeconds
	}
	return 0
}

func (x *ActualBackup) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ActualBackup) GetSizeBytes() uint64 {
	if x != nil && x.SizeBytes != nil {
		return *x.SizeBytes
	}
	return 0
}

func (x *ActualBackup) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// HealthReport contains host resource usage and per-cluster health.
type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostMetrics   *HostMetrics           `protobuf:"bytes,1,opt,name=host_metrics,json=hostMetrics,proto3" json:"host_metrics,omitempty"`
	Clusters      []*ClusterHealth       `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_orca_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{20}
}

func (x *HealthReport) GetHostMetrics() *HostMetrics {
	if x != nil {
		return x.HostMetrics
	}
	return nil
}

func (x *HealthReport) GetClusters() []*ClusterHealth {
	if x != nil {
		return x.Clusters
	}
	return nil
}

// HostMetrics describes resource use on the agent's host.
type HostMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent  float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes    uint64                 `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   uint64                 `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_orca_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{21}
}

func (x *HostMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *HostMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *HostMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *HostMetrics) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *HostMetrics) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

// ClusterHealth describes the reported health of one Postgres cluster.
type ClusterHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status        ClusterStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=orca.v1.ClusterStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterHealth) Reset() {
	*x = ClusterHealth{}
	mi := &file_orca_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterHealth) ProtoMessage() {}

func (x *ClusterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterHealth.ProtoReflect.Descriptor instead.
func (*ClusterHealth) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{22}
}

func (x *ClusterHealth) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterHealth) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

var File_orca_proto protoreflect.FileDescriptor

const file_orca_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"orca.proto\x12\aorca.v1\"Q\n" +
	"\x13DesiredStateMessage\x12:\n" +
	"\rdesired_state\x18\x01 \x01(\v2\x15.orca.v1.DesiredStateR\fdesiredState\"\xf2\x02\n" +
	"\x12AgentReportMessage\x127\n" +
	"\factual_state\x18\x01 \x01(\v2\x14.orca.v1.ActualStateR\vactualState\x12:\n" +
	"\rhealth_report\x18\x02 \x01(\v2\x15.orca.v1.HealthReportR\fhealthReport\x12T\n" +
	"\x16reconciliation_results\x18\x03 \x03(\v2\x1d.orca.v1.ReconciliationResultR\x15reconciliationResults\x124\n" +
	"\x16desired_state_revision\x18\x04 \x01(\tR\x14desiredStateRevision\x12[\n" +
	"\x19restore_operation_reports\x18\x05 \x03(\v2\x1f.orca.v1.RestoreOperationReportR\x17restoreOperationReports\"\x9c\x01\n" +
	"\x14ReconciliationResult\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\"\xc5\x01\n" +
	"\fDesiredState\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x120\n" +
	"\bclusters\x18\x02 \x03(\v2\x14.orca.v1.ClusterSpecR\bclusters\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12H\n" +
	"\x12restore_operations\x18\x04 \x03(\v2\x19.orca.v1.RestoreOperationR\x11restoreOperations\"\xa1\x02\n" +
	"\x10RestoreOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent\x12*\n" +
	"\x11source_cluster_id\x18\x04 \x01(\tR\x0fsourceClusterId\x12@\n" +
	"\x0etarget_cluster\x18\x05 \x01(\v2\x14.orca.v1.ClusterSpecH\x00R\rtargetCluster\x88\x01\x01\x12\x1f\n" +
	"\vtarget_time\x18\x06 \x01(\tR\n" +
	"targetTime\x12/\n" +
	"\x13request_fingerprint\x18\a \x01(\tR\x12requestFingerprintB\x11\n" +
	"\x0f_target_cluster\"\xf2\x04\n" +
	"\x16RestoreOperationReport\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12/\n" +
	"\x13destructive_started\x18\a \x01(\bR\x12destructiveStarted\x12 \n" +
	"\vcancellable\x18\b \x01(\bR\vcancellable\x12-\n" +
	"\x12rollback_available\x18\t \x01(\bR\x11rollbackAvailable\x12!\n" +
	"\fbackup_label\x18\n" +
	" \x01(\tR\vbackupLabel\x12+\n" +
	"\x11recovery_earliest\x18\v \x01(\tR\x10recoveryEarliest\x12'\n" +
	"\x0frecovery_latest\x18\f \x01(\tR\x0erecoveryLatest\x12)\n" +
	"\x10postgres_version\x18\r \x01(\tR\x0fpostgresVersion\x12%\n" +
	"\x0erequired_bytes\x18\x0e \x01(\x04R\rrequiredBytes\x12'\n" +
	"\x0favailable_bytes\x18\x0f \x01(\x04R\x0eavailableBytes\x12\x1d\n" +
	"\n" +
	"started_at\x18\x10 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x11 \x01(\tR\vcompletedAt\"\xc8\x04\n" +
	"\vClusterSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\x06params\x18\x03 \x03(\v2 .orca.v1.ClusterSpec.ParamsEntryR\x06params\x120\n" +
	"\breplicas\x18\x04 \x03(\v2\x14.orca.v1.ReplicaSpecR\breplicas\x12:\n" +
	"\n" +
	"pg_bouncer\x18\x05 \x01(\v2\x16.orca.v1.PgBouncerSpecH\x00R\tpgBouncer\x88\x01\x01\x123\n" +
	"\tdatabases\x18\x06 \x03(\v2\x15.orca.v1.DatabaseSpecR\tdatabases\x12>\n" +
	"\fpg_back_rest\x18\a \x01(\v2\x17.orca.v1.PgBackRestSpecH\x01R\n" +
	"pgBackRest\x88\x01\x01\x12-\n" +
	"\x12enabled_extensions\x18\b \x03(\tR\x11enabledExtensions\x12.\n" +
	"\x06pg_hba\x18\t \x01(\v2\x12.orca.v1.PgHbaSpecH\x02R\x05pgHba\x88\x01\x01\x12-\n" +
	"\x12restart_generation\x18\n" +
	" \x01(\x04R\x11restartGeneration\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_pg_bouncerB\x0f\n" +
	"\r_pg_back_restB\t\n" +
	"\a_pg_hba\"5\n" +
	"\tPgHbaSpec\x12(\n" +
	"\x05rules\x18\x01 \x03(\v2\x12.orca.v1.PgHbaRuleR\x05rules\"\x81\x01\n" +
	"\tPgHbaRule\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\"\x1d\n" +
	"\vReplicaSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\fDatabaseSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8e\x02\n" +
	"\rPgBouncerSpec\x12\x1b\n" +
	"\tpool_mode\x18\x01 \x01(\tR\bpoolMode\x12'\n" +
	"\x0fmax_connections\x18\x02 \x01(\rR\x0emaxConnections\x12*\n" +
	"\x11reserve_pool_size\x18\x03 \x01(\rR\x0freservePoolSize\x12?\n" +
	"\x1creserve_pool_timeout_seconds\x18\x04 \x01(\rR\x19reservePoolTimeoutSeconds\x12'\n" +
	"\x0fpublish_address\x18\x05 \x01(\tR\x0epublishAddress\x12!\n" +
	"\fpublish_port\x18\x06 \x01(\rR\vpublishPort\"\xb0\x01\n" +
	"\x0ePgBackRestSpec\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12%\n" +
	"\x0eretention_full\x18\x02 \x01(\rR\rretentionFull\x12%\n" +
	"\x0eretention_diff\x18\x03 \x01(\rR\rretentionDiff\x123\n" +
	"\bschedule\x18\x04 \x01(\v2\x17.orca.v1.BackupScheduleR\bschedule\"\xac\x01\n" +
	"\x0eBackupSchedule\x122\n" +
	"\x15full_interval_seconds\x18\x01 \x01(\x04R\x13fullIntervalSeconds\x122\n" +
	"\x15diff_interval_seconds\x18\x02 \x01(\x04R\x13diffIntervalSeconds\x122\n" +
	"\x15incr_interval_seconds\x18\x03 \x01(\x04R\x13incrIntervalSeconds\"A\n" +
	"\vActualState\x122\n" +
	"\bclusters\x18\x01 \x03(\v2\x16.orca.v1.ActualClusterR\bclusters\"\x84\f\n" +
	"\rActualCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x122\n" +
	"\breplicas\x18\x05 \x03(\v2\x16.orca.v1.ActualReplicaR\breplicas\x12<\n" +
	"\n" +
	"pg_bouncer\x18\x06 \x01(\v2\x18.orca.v1.ActualPgBouncerH\x00R\tpgBouncer\x88\x01\x01\x122\n" +
	"\x06backup\x18\a \x01(\v2\x15.orca.v1.ActualBackupH\x01R\x06backup\x88\x01\x01\x12-\n" +
	"\x12enabled_extensions\x18\b \x03(\tR\x11enabledExtensions\x12P\n" +
	"\x0eapplied_params\x18\t \x03(\v2).orca.v1.ActualCluster.AppliedParamsEntryR\rappliedParams\x12#\n" +
	"\rvolume_exists\x18\n" +
	" \x01(\bR\fvolumeExists\x12\x14\n" +
	"\x05image\x18\v \x01(\tR\x05image\x12*\n" +
	"\x0epostgres_ready\x18\f \x01(\bH\x02R\rpostgresReady\x88\x01\x01\x12\\\n" +
	"\x12extension_versions\x18\r \x03(\v2-.orca.v1.ActualCluster.ExtensionVersionsEntryR\x11extensionVersions\x12l\n" +
	"\x18extension_update_methods\x18\x0e \x03(\v22.orca.v1.ActualCluster.ExtensionUpdateMethodsEntryR\x16extensionUpdateMethods\x124\n" +
	"\fpg_hba_rules\x18\x0f \x03(\v2\x12.orca.v1.PgHbaRuleR\n" +
	"pgHbaRules\x12&\n" +
	"\x0fpg_hba_observed\x18\x10 \x01(\bR\rpgHbaObserved\x12#\n" +
	"\rnetwork_cidrs\x18\x11 \x03(\tR\fnetworkCidrs\x127\n" +
	"\x18pg_hba_replication_cidrs\x18\x12 \x03(\tR\x15pgHbaReplicationCidrs\x12V\n" +
	"\x10parameter_states\x18\x13 \x03(\v2+.orca.v1.ActualCluster.ParameterStatesEntryR\x0fparameterStates\x12/\n" +
	"\x13parameters_observed\x18\x14 \x01(\bR\x12parametersObserved\x12<\n" +
	"\x1aapplied_restart_generation\x18\x15 \x01(\x04R\x18appliedRestartGeneration\x12!\n" +
	"\fnetwork_name\x18\x16 \x01(\tR\vnetworkName\x12)\n" +
	"\x11pg_hba_pool_cidrs\x18\x17 \x03(\tR\x0epgHbaPoolCidrs\x1a@\n" +
	"\x12AppliedParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16ExtensionVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aI\n" +
	"\x1bExtensionUpdateMethodsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ac\n" +
	"\x14ParameterStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.orca.v1.PostgresParameterStateR\x05value:\x028\x01B\r\n" +
	"\v_pg_bouncerB\t\n" +
	"\a_backupB\x11\n" +
	"\x0f_postgres_ready\"\xde\x01\n" +
	"\x16PostgresParameterState\x12\x18\n" +
	"\asetting\x18\x01 \x01(\tR\asetting\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12#\n" +
	"\rupdate_method\x18\x04 \x01(\tR\fupdateMethod\x12'\n" +
	"\x0fpending_restart\x18\x05 \x01(\bR\x0ependingRestart\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x18\n" +
	"\aapplied\x18\a \x01(\bR\aapplied\"\xab\x06\n" +
	"\rActualReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x127\n" +
	"\x15replication_lag_bytes\x18\x04 \x01(\x04H\x00R\x13replicationLagBytes\x88\x01\x01\x120\n" +
	"\x11standby_connected\x18\x05 \x01(\bH\x01R\x10standbyConnected\x88\x01\x01\x12'\n" +
	"\x0fstreaming_state\x18\x06 \x01(\tR\x0estreamingState\x121\n" +
	"\x15last_wal_received_lsn\x18\a \x01(\tR\x12lastWalReceivedLsn\x121\n" +
	"\x15last_wal_replayed_lsn\x18\b \x01(\tR\x12lastWalReplayedLsn\x124\n" +
	"\x16replication_lag_status\x18\t \x01(\tR\x14replicationLagStatus\x124\n" +
	"\fpg_hba_rules\x18\n" +
	" \x03(\v2\x12.orca.v1.PgHbaRuleR\n" +
	"pgHbaRules\x12&\n" +
	"\x0fpg_hba_observed\x18\v \x01(\bR\rpgHbaObserved\x12P\n" +
	"\x0eapplied_params\x18\f \x03(\v2).orca.v1.ActualReplica.AppliedParamsEntryR\rappliedParams\x12/\n" +
	"\x13parameters_observed\x18\r \x01(\bR\x12parametersObserved\x12!\n" +
	"\fnetwork_name\x18\x0e \x01(\tR\vnetworkName\x12)\n" +
	"\x11pg_hba_pool_cidrs\x18\x0f \x03(\tR\x0epgHbaPoolCidrs\x1a@\n" +
	"\x12AppliedParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x18\n" +
	"\x16_replication_lag_bytesB\x14\n" +
	"\x12_standby_connected\"\xe9\x03\n" +
	"\x0fActualPgBouncer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\x12?\n" +
	"\x19active_client_connections\x18\x04 \x01(\rH\x00R\x17activeClientConnections\x88\x01\x01\x129\n" +
	"\x16max_client_connections\x18\x05 \x01(\rH\x01R\x14maxClientConnections\x88\x01\x01\x12;\n" +
	"\x17admin_console_reachable\x18\x06 \x01(\bH\x02R\x15adminConsoleReachable\x88\x01\x01\x12!\n" +
	"\fnetwork_name\x18\a \x01(\tR\vnetworkName\x12+\n" +
	"\x11published_address\x18\b \x01(\tR\x10publishedAddress\x12%\n" +
	"\x0epublished_port\x18\t \x01(\rR\rpublishedPortB\x1c\n" +
	"\x1a_active_client_connectionsB\x19\n" +
	"\x17_max_client_connectionsB\x1a\n" +
	"\x18_admin_console_reachable\"\xcf\x01\n" +
	"\fActualBackup\x12>\n" +
	"\x19last_success_unix_seconds\x18\x01 \x01(\x03H\x00R\x16lastSuccessUnixSeconds\x88\x01\x01\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\"\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04H\x01R\tsizeBytes\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB\x1c\n" +
	"\x1a_last_success_unix_secondsB\r\n" +
	"\v_size_bytes\"{\n" +
	"\fHealthReport\x127\n" +
	"\fhost_metrics\x18\x01 \x01(\v2\x14.orca.v1.HostMetricsR\vhostMetrics\x122\n" +
	"\bclusters\x18\x02 \x03(\v2\x16.orca.v1.ClusterHealthR\bclusters\"\xe5\x01\n" +
	"\vHostMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x04R\x0ediskTotalBytes\"^\n" +
	"\rClusterHealth\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.orca.v1.ClusterStatusR\x06status*\x9d\x01\n" +
	"\rClusterStatus\x12\x1e\n" +
	"\x1aCLUSTER_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CLUSTER_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16CLUSTER_STATUS_HEALTHY\x10\x02\x12\x1b\n" +
	"\x17CLUSTER_STATUS_DEGRADED\x10\x03\x12\x17\n" +
	"\x13CLUSTER_STATUS_DOWN\x10\x04B&Z$github.com/swapnil404/orca/pkg/typesb\x06proto3"

var (
	file_orca_proto_rawDescOnce sync.Once
	file_orca_proto_rawDescData []byte
)

func file_orca_proto_rawDescGZIP() []byte {
	file_orca_proto_rawDescOnce.Do(func() {
		file_orca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orca_proto_rawDesc), len(file_orca_proto_rawDesc)))
	})
	return file_orca_proto_rawDescData
}

var file_orca_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orca_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_orca_proto_goTypes = []any{
	(ClusterStatus)(0),             // 0: orca.v1.ClusterStatus
	(*DesiredStateMessage)(nil),    // 1: orca.v1.DesiredStateMessage
	(*AgentReportMessage)(nil),     // 2: orca.v1.AgentReportMessage
	(*ReconciliationResult)(nil),   // 3: orca.v1.ReconciliationResult
	(*DesiredState)(nil),           // 4: orca.v1.DesiredState
	(*RestoreOperation)(nil),       // 5: orca.v1.RestoreOperation
	(*RestoreOperationReport)(nil), // 6: orca.v1.RestoreOperationReport
	(*ClusterSpec)(nil),            // 7: orca.v1.ClusterSpec
	(*PgHbaSpec)(nil),              // 8: orca.v1.PgHbaSpec
	(*PgHbaRule)(nil),              // 9: orca.v1.PgHbaRule
	(*ReplicaSpec)(nil),            // 10: orca.v1.ReplicaSpec
	(*DatabaseSpec)(nil),           // 11: orca.v1.DatabaseSpec
	(*PgBouncerSpec)(nil),          // 12: orca.v1.PgBouncerSpec
	(*PgBackRestSpec)(nil),         // 13: orca.v1.PgBackRestSpec
	(*BackupSchedule)(nil),         // 14: orca.v1.BackupSchedule
	(*ActualState)(nil),            // 15: orca.v1.ActualState
	(*ActualCluster)(nil),          // 16: orca.v1.ActualCluster
	(*PostgresParameterState)(nil), // 17: orca.v1.PostgresParameterState
	(*ActualReplica)(nil),          // 18: orca.v1.ActualReplica
	(*ActualPgBouncer)(nil),        // 19: orca.v1.ActualPgBouncer
	(*ActualBackup)(nil),           // 20: orca.v1.ActualBackup
	(*HealthReport)(nil),           // 21: orca.v1.HealthReport
	(*HostMetrics)(nil),            // 22: orca.v1.HostMetrics
	(*ClusterHealth)(nil),          // 23: orca.v1.ClusterHealth
	nil,                            // 24: orca.v1.ClusterSpec.ParamsEntry
	nil,                            // 25: orca.v1.ActualCluster.AppliedParamsEntry
	nil,                            // 26: orca.v1.ActualCluster.ExtensionVersionsEntry
	nil,                            // 27: orca.v1.ActualCluster.ExtensionUpdateMethodsEntry
	nil,                            // 28: orca.v1.ActualCluster.ParameterStatesEntry
	nil,                            // 29: orca.v1.ActualReplica.AppliedParamsEntry
}
var file_orca_proto_depIdxs = []int32{
	4,  // 0: orca.v1.DesiredStateMessage.desired_state:type_name -> orca.v1.DesiredState
	15, // 1: orca.v1.AgentReportMessage.actual_state:type_name -> orca.v1.ActualState
	21, // 2: orca.v1.AgentReportMessage.health_report:type_name -> orca.v1.HealthReport
	3,  // 3: orca.v1.AgentReportMessage.reconciliation_results:type_name -> orca.v1.ReconciliationResult
	6,  // 4: orca.v1.AgentReportMessage.restore_operation_reports:type_name -> orca.v1.RestoreOperationReport
	7,  // 5: orca.v1.DesiredState.clusters:type_name -> orca.v1.ClusterSpec
	5,  // 6: orca.v1.DesiredState.restore_operations:type_name -> orca.v1.RestoreOperation
	7,  // 7: orca.v1.RestoreOperation.target_cluster:type_name -> orca.v1.ClusterSpec
	24, // 8: orca.v1.ClusterSpec.params:type_name -> orca.v1.ClusterSpec.ParamsEntry
	10, // 9: orca.v1.ClusterSpec.replicas:type_name -> orca.v1.ReplicaSpec
	12, // 10: orca.v1.ClusterSpec.pg_bouncer:type_name -> orca.v1.PgBouncerSpec
	11, // 11: orca.v1.ClusterSpec.databases:type_name -> orca.v1.DatabaseSpec
	13, // 12: orca.v1.ClusterSpec.pg_back_rest:type_name -> orca.v1.PgBackRestSpec
	8,  // 13: orca.v1.ClusterSpec.pg_hba:type_name -> orca.v1.PgHbaSpec
	9,  // 14: orca.v1.PgHbaSpec.rules:type_name -> orca.v1.PgHbaRule
	14, // 15: orca.v1.PgBackRestSpec.schedule:type_name -> orca.v1.BackupSchedule
	16, // 16: orca.v1.ActualState.clusters:type_name -> orca.v1.ActualCluster
	18, // 17: orca.v1.ActualCluster.replicas:type_name -> orca.v1.ActualReplica
	19, // 18: orca.v1.ActualCluster.pg_bouncer:type_name -> orca.v1.ActualPgBouncer
	20, // 19: orca.v1.ActualCluster.backup:type_name -> orca.v1.ActualBackup
	25, // 20: orca.v1.ActualCluster.applied_params:type_name -> orca.v1.ActualCluster.AppliedParamsEntry
	26, // 21: orca.v1.ActualCluster.extension_versions:type_name -> orca.v1.ActualCluster.ExtensionVersionsEntry
	27, // 22: orca.v1.ActualCluster.extension_update_methods:type_name -> orca.v1.ActualCluster.ExtensionUpdateMethodsEntry
	9,  // 23: orca.v1.ActualCluster.pg_hba_rules:type_name -> orca.v1.PgHbaRule
	28, // 24: orca.v1.ActualCluster.parameter_states:type_name -> orca.v1.ActualCluster.ParameterStatesEntry
	9,  // 25: orca.v1.ActualReplica.pg_hba_rules:type_name -> orca.v1.PgHbaRule
	29, // 26: orca.v1.ActualReplica.applied_params:type_name -> orca.v1.ActualReplica.AppliedParamsEntry
	22, // 27: orca.v1.HealthReport.host_metrics:type_name -> orca.v1.HostMetrics
	23, // 28: orca.v1.HealthReport.clusters:type_name -> orca.v1.ClusterHealth
	0,  // 29: orca.v1.ClusterHealth.status:type_name -> orca.v1.ClusterStatus
	17, // 30: orca.v1.ActualCluster.ParameterStatesEntry.value:type_name -> orca.v1.PostgresParameterState
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_orca_proto_init() }
func file_orca_proto_init() {
	if File_orca_proto != nil {
		return
	}
	file_orca_proto_msgTypes[4].OneofWrappers = []any{}
	file_orca_proto_msgTypes[6].OneofWrappers = []any{}
	file_orca_proto_msgTypes[15].OneofWrappers = []any{}
	file_orca_proto_msgTypes[17].OneofWrappers = []any{}
	file_orca_proto_msgTypes[18].OneofWrappers = []any{}
	file_orca_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orca_proto_rawDesc), len(file_orca_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orca_proto_goTypes,
		DependencyIndexes: file_orca_proto_depIdxs,
		EnumInfos:         file_orca_proto_enumTypes,
		MessageInfos:      file_orca_proto_msgTypes,
	}.Build()
	File_orca_proto = out.File
	file_orca_proto_goTypes = nil
	file_orca_proto_depIdxs = nil
}
